set(_AMENT_PACKAGE_NAME "joint_msgs")
set(joint_msgs_VERSION "0.1.0")
set(joint_msgs_MAINTAINER "agibotdev <agibotdev@agibot.com>")
set(joint_msgs_BUILD_DEPENDS "std_msgs")
set(joint_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(joint_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(joint_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(joint_msgs_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs")
set(joint_msgs_TEST_DEPENDS )
set(joint_msgs_GROUP_DEPENDS )
set(joint_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(joint_msgs_DEPRECATED "")
set(joint_msgs_EXPORT_TAGS)
list(APPEND joint_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
