// Parity test: the C++ 180-D obs builder + reference clock must match the Python
// (golden.txt generated by gen_golden.py). Build (Eigen only, no AimRT/ONNX):
//   g++ -std=c++17 -I <.../a3_deploy_onnx_ref/include> -I /usr/include/eigen3 \
//       pp_parity_test.cpp -o pp_parity_test && ./pp_parity_test golden.txt
#include <cmath>
#include <cstdio>
#include <fstream>
#include <vector>

#include "a3_pingpong/pp_obs_builder.hpp"
#include "a3_pingpong/pp_reference_clock.hpp"

using namespace a3_pingpong;

int main(int argc, char** argv) {
  const char* path = argc > 1 ? argv[1] : "golden.txt";
  std::ifstream f(path);
  if (!f) { std::fprintf(stderr, "cannot open %s\n", path); return 2; }
  std::vector<double> t;
  for (double v; f >> v;) t.push_back(v);
  size_t i = 0;
  auto vec = [&](int n) { Eigen::VectorXd v(n); for (int k = 0; k < n; ++k) v[k] = t[i++]; return v; };
  auto v3 = [&]() { Vec3 v; v << t[i], t[i + 1], t[i + 2]; i += 3; return v; };
  auto v4 = [&]() { Vec4 v; v << t[i], t[i + 1], t[i + 2], t[i + 3]; i += 4; return v; };
  auto v2 = [&]() { Vec2 v; v << t[i], t[i + 1]; i += 2; return v; };

  PpRefs refs;
  refs.joint_pos = vec(31);
  refs.joint_vel = vec(31);
  refs.anchor_pos_w = v3();
  refs.anchor_quat_w = v4();

  PpRobotState st;
  st.base_pos_w = v3(); st.base_quat_w = v4();
  st.torso_pos_w = v3(); st.torso_quat_w = v4();
  st.base_ang_vel_b = v3();
  st.q = vec(31); st.qd = vec(31);

  PpRacketTarget tg;
  tg.pos_w = v3(); tg.vel_w = v3();
  tg.swing_sign = t[i++]; tg.time_to_strike = t[i++];
  tg.base_target_xy = v2();

  Eigen::VectorXd last_action = vec(31);
  Eigen::VectorXd default_q = vec(31);
  Eigen::VectorXd expected = vec(180);

  Eigen::VectorXd obs = build_obs_180(refs, st, tg, last_action, default_q);
  double max_err = 0.0; int worst = -1;
  for (int k = 0; k < kObsDim; ++k) {
    double e = std::fabs(obs[k] - expected[k]);
    if (e > max_err) { max_err = e; worst = k; }
  }
  std::printf("[obs] max_abs_err = %.3e at idx %d\n", max_err, worst);

  // reference clock
  ClipLayout layout;
  int nclk = static_cast<int>(t[i++]);
  int clk_fail = 0;
  for (int c = 0; c < nclk; ++c) {
    int cid = static_cast<int>(t[i++]);
    double tts = t[i++];
    int exp_ts = static_cast<int>(t[i++]);
    int got = layout.time_step_for(cid, tts);
    if (got != exp_ts) {
      clk_fail++;
      std::printf("[clk] MISMATCH clip=%d tts=%.3f got=%d exp=%d\n", cid, tts, got, exp_ts);
    }
  }
  int sf0 = static_cast<int>(t[i++]), sf1 = static_cast<int>(t[i++]);
  bool sf_ok = (layout.strike_frame(0) == sf0) && (layout.strike_frame(1) == sf1);
  std::printf("[clk] %d/%d cases ok; strike_frames C++=(%d,%d) py=(%d,%d) %s\n",
              nclk - clk_fail, nclk, layout.strike_frame(0), layout.strike_frame(1),
              sf0, sf1, sf_ok ? "OK" : "FAIL");

  bool pass = (max_err < 1e-9) && (clk_fail == 0) && sf_ok;
  std::printf("%s\n", pass ? "PARITY PASS" : "PARITY FAIL");
  return pass ? 0 : 1;
}
