#!/usr/bin/env python3
"""Build one full 31-DOF, 50 Hz command payload under a frozen contract.

The source NPZ remains a kinematic reference.  Only the waist and right arm
come from it in the first fixed-stand diagnostic contract; every remaining
joint is explicitly generated by the contract baseline.  This prevents the
old implicit "whatever other controller owns the legs" assumption.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from a3_strike_contract import canonical_command_payload_sha256, sha256_file, validate_executor_contract


ISAAC_31_DOF = (
    "left_hip_pitch_joint", "right_hip_pitch_joint", "waist_yaw_joint", "left_hip_roll_joint", "right_hip_roll_joint", "waist_roll_joint", "left_hip_yaw_joint", "right_hip_yaw_joint", "waist_pitch_joint", "left_knee_joint", "right_knee_joint", "head_yaw_joint", "left_shoulder_pitch_joint", "right_shoulder_pitch_joint", "left_ankle_pitch_joint", "right_ankle_pitch_joint", "head_pitch_joint", "left_shoulder_roll_joint", "right_shoulder_roll_joint", "left_ankle_roll_joint", "right_ankle_roll_joint", "left_shoulder_yaw_joint", "right_shoulder_yaw_joint", "left_elbow_joint", "right_elbow_joint", "left_wrist_roll_joint", "right_wrist_roll_joint", "left_wrist_pitch_joint", "right_wrist_pitch_joint", "left_wrist_yaw_joint", "right_wrist_yaw_joint",
)

DEFAULT_ANGLES = {
    "left_hip_pitch_joint": -0.1311, "right_hip_pitch_joint": -0.1311,
    "left_hip_roll_joint": 0.0056, "right_hip_roll_joint": -0.0056,
    "left_hip_yaw_joint": -0.0348, "right_hip_yaw_joint": 0.0348,
    "left_knee_joint": 0.2468, "right_knee_joint": 0.2468,
    "left_ankle_pitch_joint": -0.1204, "right_ankle_pitch_joint": -0.1204,
    "left_ankle_roll_joint": -0.0078, "right_ankle_roll_joint": 0.0078,
    "left_shoulder_pitch_joint": 0.3, "right_shoulder_pitch_joint": 0.3,
    "left_shoulder_roll_joint": 0.12, "right_shoulder_roll_joint": -0.12,
    "left_elbow_joint": 0.8, "right_elbow_joint": 0.8,
}
KP = {name: 20.0 for name in ISAAC_31_DOF}
KD = {name: 2.0 for name in ISAAC_31_DOF}
for name in ISAAC_31_DOF:
    if "shoulder_pitch" in name or "shoulder_roll" in name:
        KP[name], KD[name] = 40.0, 3.0
    elif "shoulder_yaw" in name or "elbow" in name or "wrist_roll" in name:
        KP[name] = 30.0
    elif "hip_pitch" in name or "hip_yaw" in name:
        KP[name], KD[name] = 80.0, 3.0
    elif "hip_roll" in name:
        KP[name], KD[name] = 120.0, 4.0
    elif "knee" in name:
        KP[name], KD[name] = 250.0, 8.0
    elif "ankle" in name:
        KP[name] = 50.0
KP["waist_yaw_joint"], KD["waist_yaw_joint"] = 85.0, 3.0
KP["waist_roll_joint"], KP["waist_pitch_joint"] = 50.0, 50.0
KP["head_yaw_joint"], KP["head_pitch_joint"] = 40.0, 40.0


def _source_joint_names(archive: np.lib.npyio.NpzFile) -> tuple[str, ...]:
    if "joint_names" in archive.files:
        names = tuple(str(x) for x in archive["joint_names"].tolist())
    else:
        names = ISAAC_31_DOF
    if len(names) != 31 or len(set(names)) != 31:
        raise ValueError("source reference must declare 31 unique joint names")
    return names


def build_payload(source: Path, contract: dict) -> tuple[dict[str, np.ndarray], str]:
    validate_executor_contract(contract)
    with np.load(source, allow_pickle=False) as archive:
        if "joint_pos" not in archive.files or "fps" not in archive.files:
            raise ValueError(f"{source}: expected joint_pos and fps")
        q_reference = np.asarray(archive["joint_pos"], dtype=np.float64)
        fps = float(np.asarray(archive["fps"]).reshape(-1)[0])
        source_names = _source_joint_names(archive)
    if q_reference.ndim != 2 or q_reference.shape[1] != 31 or not np.all(np.isfinite(q_reference)):
        raise ValueError(f"{source}: joint_pos must be finite [T,31]")
    if fps != 50.0:
        raise ValueError(f"{source}: fps={fps}; first contract requires exactly 50 Hz reference")
    output_names = tuple(str(joint["joint_name"]) for joint in contract["joints"])
    source_index = {name: index for index, name in enumerate(source_names)}
    reference_in_contract_order = np.stack([q_reference[:, source_index[name]] for name in output_names], axis=1)
    q_des = np.tile(np.asarray([DEFAULT_ANGLES.get(name, 0.0) for name in output_names]), (len(q_reference), 1))
    strike = np.asarray([joint["ownership"] == "strike_optimized" for joint in contract["joints"]])
    q_des[:, strike] = reference_in_contract_order[:, strike]
    payload = {
        "timestamps_s": np.arange(len(q_reference), dtype=np.float64) / fps,
        "q_des": q_des,
        "dq_des": np.zeros_like(q_des),
        "tau_ff": np.zeros_like(q_des),
        "kp": np.tile(np.asarray([KP[name] for name in output_names]), (len(q_reference), 1)),
        "kd": np.tile(np.asarray([KD[name] for name in output_names]), (len(q_reference), 1)),
        # Keep the Unicode manifest last.  The vendor cnpy reader handles
        # numeric arrays correctly but miscounts Unicode element bytes; after
        # the numeric payloads it can no longer corrupt the command arrays.
        "joint_names": np.asarray(output_names),
    }
    digest = canonical_command_payload_sha256(**payload)
    return payload, digest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-npz", type=Path, required=True)
    parser.add_argument("--executor-contract", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    reference = args.reference_npz.expanduser().resolve()
    contract_path = args.executor_contract.expanduser().resolve()
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    payload, digest = build_payload(reference, contract)
    output = args.output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    # The vendor RobotIO replay uses cnpy's direct ZIP reader.  Its deflate
    # path cannot read NumPy's current compressed NPZ stream reliably, while
    # stored NPZ entries preserve the exact same arrays and are portable to
    # both cnpy and NumPy.
    np.savez(output, **payload)
    metadata = {
        "schema_version": 1,
        "executor_contract_id": contract["executor_contract_id"],
        "reference_npz": str(reference),
        "reference_npz_sha256": sha256_file(reference),
        "executor_contract_sha256": sha256_file(contract_path),
        "command_sha256": digest,
        "command_semantics": "canonical_command_payload_v1",
        "npz_container": "stored_uncompressed_npz_v1",
        "policy_hz": 50.0,
        "note": "Fixed-stand diagnostic command; not approved for training or deployment.",
    }
    output.with_suffix(".command.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
