/**
 * @file time_manipulator.aimrt_rpc.pb.h
 * @brief This file was generated by protoc-gen-aimrt_rpc which is a self-defined pb compiler plugin, do not edit it!!!
 */
#pragma once

#include <future>

#include "aimrt_module_cpp_interface/rpc/rpc_handle.h"
#include "aimrt_module_cpp_interface/rpc/rpc_status.h"
#include "aimrt_module_cpp_interface/util/version.h"

#include "aimrt_module_cpp_interface/co/task.h"

#include "aimrt_module_cpp_interface.h"

#include "time_manipulator.pb.h"

static_assert(1000000 <= AIMRT_RUNTIME_VERSION_INT,
              "AIMRT_RUNTIME_VERSION is older than generated code version 1.0.0");
static_assert(AIMRT_MIN_GENCODE_VERSION_INT <= 1000000,
              "AIMRT_MIN_GENCODE_VERSION is greater than generated code version 1.0.0");


namespace aimrt {
namespace protocols {
namespace time_manipulator_plugin {

class TimeManipulatorServiceSyncService : public aimrt::rpc::ServiceBase {
 public:
  TimeManipulatorServiceSyncService();
  ~TimeManipulatorServiceSyncService() override = default;
  virtual aimrt::rpc::Status SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
  virtual aimrt::rpc::Status Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
  virtual aimrt::rpc::Status GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
};

class TimeManipulatorServiceAsyncService : public aimrt::rpc::ServiceBase {
 public:
  TimeManipulatorServiceAsyncService();
  ~TimeManipulatorServiceAsyncService() override = default;
  virtual void SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    callback(aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED));
  }
  virtual void Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    callback(aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED));
  }
  virtual void GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    callback(aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED));
  }
};

class TimeManipulatorServiceCoService : public aimrt::rpc::CoServiceBase {
 public:
  TimeManipulatorServiceCoService();
  ~TimeManipulatorServiceCoService() override = default;
  virtual aimrt::co::Task<aimrt::rpc::Status> SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    co_return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
  virtual aimrt::co::Task<aimrt::rpc::Status> Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    co_return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
  virtual aimrt::co::Task<aimrt::rpc::Status> GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    co_return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
};


bool RegisterTimeManipulatorServiceClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
bool RegisterTimeManipulatorServiceClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref);

class TimeManipulatorServiceSyncProxy : public aimrt::rpc::SyncProxyBase {
 public:
  explicit TimeManipulatorServiceSyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit TimeManipulatorServiceSyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~TimeManipulatorServiceSyncProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref, service_name);
  }
  aimrt::rpc::Status SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::rpc::Status SetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return SetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
  aimrt::rpc::Status Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::rpc::Status Pause(
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return Pause(aimrt::rpc::ContextRef(), req, rsp);
  }
  aimrt::rpc::Status GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::rpc::Status GetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return GetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class TimeManipulatorServiceAsyncProxy : public aimrt::rpc::AsyncProxyBase {
 public:
  explicit TimeManipulatorServiceAsyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit TimeManipulatorServiceAsyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~TimeManipulatorServiceAsyncProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref, service_name);
  }
  void SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback);

  void SetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    SetTimeRatio(aimrt::rpc::ContextRef(), req, rsp, std::move(callback));
  }
  void Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback);

  void Pause(
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    Pause(aimrt::rpc::ContextRef(), req, rsp, std::move(callback));
  }
  void GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback);

  void GetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    GetTimeRatio(aimrt::rpc::ContextRef(), req, rsp, std::move(callback));
  }
};


class TimeManipulatorServiceFutureProxy : public aimrt::rpc::FutureProxyBase {
 public:
  explicit TimeManipulatorServiceFutureProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit TimeManipulatorServiceFutureProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~TimeManipulatorServiceFutureProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref, service_name);
  }
  std::future<aimrt::rpc::Status> SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  std::future<aimrt::rpc::Status> SetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return SetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
  std::future<aimrt::rpc::Status> Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  std::future<aimrt::rpc::Status> Pause(
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return Pause(aimrt::rpc::ContextRef(), req, rsp);
  }
  std::future<aimrt::rpc::Status> GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  std::future<aimrt::rpc::Status> GetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return GetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class TimeManipulatorServiceCoProxy : public aimrt::rpc::CoProxyBase {
 public:
  explicit TimeManipulatorServiceCoProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit TimeManipulatorServiceCoProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~TimeManipulatorServiceCoProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterTimeManipulatorServiceClientFunc(rpc_handle_ref, service_name);
  }
  aimrt::co::Task<aimrt::rpc::Status> SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::co::Task<aimrt::rpc::Status> SetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return SetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
  aimrt::co::Task<aimrt::rpc::Status> Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::co::Task<aimrt::rpc::Status> Pause(
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return Pause(aimrt::rpc::ContextRef(), req, rsp);
  }
  aimrt::co::Task<aimrt::rpc::Status> GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp);

  aimrt::co::Task<aimrt::rpc::Status> GetTimeRatio(
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) {
    return GetTimeRatio(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class TimeManipulatorServiceCoClient {
 public:
  /**
   * @brief Initialize the service resource based on AimRT Context.
   */
  void Init(const std::shared_ptr<::aimrt::context::Context> & ctx_ptr, std::string service_name = "");

 public:
  ::aimrt::context::res::Client<::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> SetTimeRatio;

  ::aimrt::context::res::Client<::aimrt::protocols::time_manipulator_plugin::PauseReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> Pause;

  ::aimrt::context::res::Client<::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> GetTimeRatio;


 public:
  static std::vector<std::string> GetMethodNames(std::string service_name = {});

};

// Forward declaration
class TimeManipulatorServiceAimRTImpl;

class TimeManipulatorServiceCoServer : public std::enable_shared_from_this<TimeManipulatorServiceCoServer> {
 public:
  void Init(const std::shared_ptr<::aimrt::context::Context> & ctx_ptr, std::string service_name = "");

 public:
  ::aimrt::context::res::Server<::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> SetTimeRatio;

  ::aimrt::context::res::Server<::aimrt::protocols::time_manipulator_plugin::PauseReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> Pause;

  ::aimrt::context::res::Server<::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq, ::aimrt::protocols::time_manipulator_plugin::CommonRsp> GetTimeRatio;


 public:
  static std::vector<std::string> GetMethodNames(std::string service_name = {});

 private:
  std::weak_ptr<::aimrt::context::Context> ctx_weak_ptr_;
  std::shared_ptr<TimeManipulatorServiceAimRTImpl> impl_;
};

class TimeManipulatorServiceAimRTImpl final : public TimeManipulatorServiceCoService {
 public:
  explicit TimeManipulatorServiceAimRTImpl(
      std::weak_ptr<::aimrt::context::Context> weak_ctx_ptr,
      std::shared_ptr<TimeManipulatorServiceCoServer> res);

  aimrt::co::Task<aimrt::rpc::Status> SetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) override;

  aimrt::co::Task<aimrt::rpc::Status> Pause(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::PauseReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) override;

  aimrt::co::Task<aimrt::rpc::Status> GetTimeRatio(
      aimrt::rpc::ContextRef ctx_ref,
      const ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq& req,
      ::aimrt::protocols::time_manipulator_plugin::CommonRsp& rsp) override;


 private:
  std::weak_ptr<::aimrt::context::Context> weak_ctx_ptr_;
  std::shared_ptr<TimeManipulatorServiceCoServer> res_;
};

}  // namespace time_manipulator_plugin
}  // namespace protocols
}  // namespace aimrt

