// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_command.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_joint_5fcommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_joint_5fcommand_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_joint_5fcommand_2eproto;
namespace aimrt {
namespace protocols {
namespace sensor {
class JointCommand;
struct JointCommandDefaultTypeInternal;
extern JointCommandDefaultTypeInternal _JointCommand_default_instance_;
class JointCommandArray;
struct JointCommandArrayDefaultTypeInternal;
extern JointCommandArrayDefaultTypeInternal _JointCommandArray_default_instance_;
}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt
PROTOBUF_NAMESPACE_OPEN
template<> ::aimrt::protocols::sensor::JointCommand* Arena::CreateMaybeMessage<::aimrt::protocols::sensor::JointCommand>(Arena*);
template<> ::aimrt::protocols::sensor::JointCommandArray* Arena::CreateMaybeMessage<::aimrt::protocols::sensor::JointCommandArray>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aimrt {
namespace protocols {
namespace sensor {

// ===================================================================

class JointCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.sensor.JointCommand) */ {
 public:
  inline JointCommand() : JointCommand(nullptr) {}
  ~JointCommand() override;
  explicit PROTOBUF_CONSTEXPR JointCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JointCommand(const JointCommand& from);
  JointCommand(JointCommand&& from) noexcept
    : JointCommand() {
    *this = ::std::move(from);
  }

  inline JointCommand& operator=(const JointCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointCommand& operator=(JointCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointCommand* internal_default_instance() {
    return reinterpret_cast<const JointCommand*>(
               &_JointCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JointCommand& a, JointCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(JointCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JointCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JointCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JointCommand& from) {
    JointCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.sensor.JointCommand";
  }
  protected:
  explicit JointCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPositionFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kEffortFieldNumber = 4,
    kStiffnessFieldNumber = 5,
    kDampingFieldNumber = 6,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // double position = 2;
  void clear_position();
  double position() const;
  void set_position(double value);
  private:
  double _internal_position() const;
  void _internal_set_position(double value);
  public:

  // double velocity = 3;
  void clear_velocity();
  double velocity() const;
  void set_velocity(double value);
  private:
  double _internal_velocity() const;
  void _internal_set_velocity(double value);
  public:

  // double effort = 4;
  void clear_effort();
  double effort() const;
  void set_effort(double value);
  private:
  double _internal_effort() const;
  void _internal_set_effort(double value);
  public:

  // double stiffness = 5;
  void clear_stiffness();
  double stiffness() const;
  void set_stiffness(double value);
  private:
  double _internal_stiffness() const;
  void _internal_set_stiffness(double value);
  public:

  // double damping = 6;
  void clear_damping();
  double damping() const;
  void set_damping(double value);
  private:
  double _internal_damping() const;
  void _internal_set_damping(double value);
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.sensor.JointCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    double position_;
    double velocity_;
    double effort_;
    double stiffness_;
    double damping_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_5fcommand_2eproto;
};
// -------------------------------------------------------------------

class JointCommandArray final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.sensor.JointCommandArray) */ {
 public:
  inline JointCommandArray() : JointCommandArray(nullptr) {}
  ~JointCommandArray() override;
  explicit PROTOBUF_CONSTEXPR JointCommandArray(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JointCommandArray(const JointCommandArray& from);
  JointCommandArray(JointCommandArray&& from) noexcept
    : JointCommandArray() {
    *this = ::std::move(from);
  }

  inline JointCommandArray& operator=(const JointCommandArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointCommandArray& operator=(JointCommandArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointCommandArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointCommandArray* internal_default_instance() {
    return reinterpret_cast<const JointCommandArray*>(
               &_JointCommandArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(JointCommandArray& a, JointCommandArray& b) {
    a.Swap(&b);
  }
  inline void Swap(JointCommandArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointCommandArray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointCommandArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JointCommandArray>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JointCommandArray& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JointCommandArray& from) {
    JointCommandArray::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointCommandArray* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.sensor.JointCommandArray";
  }
  protected:
  explicit JointCommandArray(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJointsFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // repeated .aimrt.protocols.sensor.JointCommand joints = 2;
  int joints_size() const;
  private:
  int _internal_joints_size() const;
  public:
  void clear_joints();
  ::aimrt::protocols::sensor::JointCommand* mutable_joints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::JointCommand >*
      mutable_joints();
  private:
  const ::aimrt::protocols::sensor::JointCommand& _internal_joints(int index) const;
  ::aimrt::protocols::sensor::JointCommand* _internal_add_joints();
  public:
  const ::aimrt::protocols::sensor::JointCommand& joints(int index) const;
  ::aimrt::protocols::sensor::JointCommand* add_joints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::JointCommand >&
      joints() const;

  // .aimrt.protocols.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::aimrt::protocols::common::Header& header() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::common::Header* release_header();
  ::aimrt::protocols::common::Header* mutable_header();
  void set_allocated_header(::aimrt::protocols::common::Header* header);
  private:
  const ::aimrt::protocols::common::Header& _internal_header() const;
  ::aimrt::protocols::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::aimrt::protocols::common::Header* header);
  ::aimrt::protocols::common::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:aimrt.protocols.sensor.JointCommandArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::JointCommand > joints_;
    ::aimrt::protocols::common::Header* header_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_5fcommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JointCommand

// string name = 1;
inline void JointCommand::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& JointCommand::name() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JointCommand::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.name)
}
inline std::string* JointCommand::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.JointCommand.name)
  return _s;
}
inline const std::string& JointCommand::_internal_name() const {
  return _impl_.name_.Get();
}
inline void JointCommand::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* JointCommand::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* JointCommand::release_name() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.JointCommand.name)
  return _impl_.name_.Release();
}
inline void JointCommand::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.JointCommand.name)
}

// double position = 2;
inline void JointCommand::clear_position() {
  _impl_.position_ = 0;
}
inline double JointCommand::_internal_position() const {
  return _impl_.position_;
}
inline double JointCommand::position() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.position)
  return _internal_position();
}
inline void JointCommand::_internal_set_position(double value) {
  
  _impl_.position_ = value;
}
inline void JointCommand::set_position(double value) {
  _internal_set_position(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.position)
}

// double velocity = 3;
inline void JointCommand::clear_velocity() {
  _impl_.velocity_ = 0;
}
inline double JointCommand::_internal_velocity() const {
  return _impl_.velocity_;
}
inline double JointCommand::velocity() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.velocity)
  return _internal_velocity();
}
inline void JointCommand::_internal_set_velocity(double value) {
  
  _impl_.velocity_ = value;
}
inline void JointCommand::set_velocity(double value) {
  _internal_set_velocity(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.velocity)
}

// double effort = 4;
inline void JointCommand::clear_effort() {
  _impl_.effort_ = 0;
}
inline double JointCommand::_internal_effort() const {
  return _impl_.effort_;
}
inline double JointCommand::effort() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.effort)
  return _internal_effort();
}
inline void JointCommand::_internal_set_effort(double value) {
  
  _impl_.effort_ = value;
}
inline void JointCommand::set_effort(double value) {
  _internal_set_effort(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.effort)
}

// double stiffness = 5;
inline void JointCommand::clear_stiffness() {
  _impl_.stiffness_ = 0;
}
inline double JointCommand::_internal_stiffness() const {
  return _impl_.stiffness_;
}
inline double JointCommand::stiffness() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.stiffness)
  return _internal_stiffness();
}
inline void JointCommand::_internal_set_stiffness(double value) {
  
  _impl_.stiffness_ = value;
}
inline void JointCommand::set_stiffness(double value) {
  _internal_set_stiffness(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.stiffness)
}

// double damping = 6;
inline void JointCommand::clear_damping() {
  _impl_.damping_ = 0;
}
inline double JointCommand::_internal_damping() const {
  return _impl_.damping_;
}
inline double JointCommand::damping() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommand.damping)
  return _internal_damping();
}
inline void JointCommand::_internal_set_damping(double value) {
  
  _impl_.damping_ = value;
}
inline void JointCommand::set_damping(double value) {
  _internal_set_damping(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.JointCommand.damping)
}

// -------------------------------------------------------------------

// JointCommandArray

// .aimrt.protocols.common.Header header = 1;
inline bool JointCommandArray::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool JointCommandArray::has_header() const {
  return _internal_has_header();
}
inline const ::aimrt::protocols::common::Header& JointCommandArray::_internal_header() const {
  const ::aimrt::protocols::common::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::common::Header&>(
      ::aimrt::protocols::common::_Header_default_instance_);
}
inline const ::aimrt::protocols::common::Header& JointCommandArray::header() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommandArray.header)
  return _internal_header();
}
inline void JointCommandArray::unsafe_arena_set_allocated_header(
    ::aimrt::protocols::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.JointCommandArray.header)
}
inline ::aimrt::protocols::common::Header* JointCommandArray::release_header() {
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::common::Header* JointCommandArray::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.JointCommandArray.header)
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::common::Header* JointCommandArray::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::common::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::aimrt::protocols::common::Header* JointCommandArray::mutable_header() {
  ::aimrt::protocols::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.JointCommandArray.header)
  return _msg;
}
inline void JointCommandArray::set_allocated_header(::aimrt::protocols::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.JointCommandArray.header)
}

// repeated .aimrt.protocols.sensor.JointCommand joints = 2;
inline int JointCommandArray::_internal_joints_size() const {
  return _impl_.joints_.size();
}
inline int JointCommandArray::joints_size() const {
  return _internal_joints_size();
}
inline void JointCommandArray::clear_joints() {
  _impl_.joints_.Clear();
}
inline ::aimrt::protocols::sensor::JointCommand* JointCommandArray::mutable_joints(int index) {
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.JointCommandArray.joints)
  return _impl_.joints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::JointCommand >*
JointCommandArray::mutable_joints() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.JointCommandArray.joints)
  return &_impl_.joints_;
}
inline const ::aimrt::protocols::sensor::JointCommand& JointCommandArray::_internal_joints(int index) const {
  return _impl_.joints_.Get(index);
}
inline const ::aimrt::protocols::sensor::JointCommand& JointCommandArray::joints(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.JointCommandArray.joints)
  return _internal_joints(index);
}
inline ::aimrt::protocols::sensor::JointCommand* JointCommandArray::_internal_add_joints() {
  return _impl_.joints_.Add();
}
inline ::aimrt::protocols::sensor::JointCommand* JointCommandArray::add_joints() {
  ::aimrt::protocols::sensor::JointCommand* _add = _internal_add_joints();
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.JointCommandArray.joints)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::JointCommand >&
JointCommandArray::joints() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.JointCommandArray.joints)
  return _impl_.joints_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_joint_5fcommand_2eproto
