// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_imu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_imu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
#include "quaternion.pb.h"
#include "vector3.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_imu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_imu_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_imu_2eproto;
namespace aimrt {
namespace protocols {
namespace sensor {
class ImuState;
struct ImuStateDefaultTypeInternal;
extern ImuStateDefaultTypeInternal _ImuState_default_instance_;
}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt
PROTOBUF_NAMESPACE_OPEN
template<> ::aimrt::protocols::sensor::ImuState* Arena::CreateMaybeMessage<::aimrt::protocols::sensor::ImuState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aimrt {
namespace protocols {
namespace sensor {

// ===================================================================

class ImuState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.sensor.ImuState) */ {
 public:
  inline ImuState() : ImuState(nullptr) {}
  ~ImuState() override;
  explicit PROTOBUF_CONSTEXPR ImuState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImuState(const ImuState& from);
  ImuState(ImuState&& from) noexcept
    : ImuState() {
    *this = ::std::move(from);
  }

  inline ImuState& operator=(const ImuState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImuState& operator=(ImuState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImuState& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImuState* internal_default_instance() {
    return reinterpret_cast<const ImuState*>(
               &_ImuState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImuState& a, ImuState& b) {
    a.Swap(&b);
  }
  inline void Swap(ImuState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImuState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImuState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImuState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImuState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImuState& from) {
    ImuState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImuState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.sensor.ImuState";
  }
  protected:
  explicit ImuState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrientationCovarianceFieldNumber = 3,
    kAngularVelocityCovarianceFieldNumber = 5,
    kLinearAccelerationCovarianceFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kOrientationFieldNumber = 2,
    kAngularVelocityFieldNumber = 4,
    kLinearAccelerationFieldNumber = 6,
  };
  // repeated double orientation_covariance = 3;
  int orientation_covariance_size() const;
  private:
  int _internal_orientation_covariance_size() const;
  public:
  void clear_orientation_covariance();
  private:
  double _internal_orientation_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_orientation_covariance() const;
  void _internal_add_orientation_covariance(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_orientation_covariance();
  public:
  double orientation_covariance(int index) const;
  void set_orientation_covariance(int index, double value);
  void add_orientation_covariance(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      orientation_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_orientation_covariance();

  // repeated double angular_velocity_covariance = 5;
  int angular_velocity_covariance_size() const;
  private:
  int _internal_angular_velocity_covariance_size() const;
  public:
  void clear_angular_velocity_covariance();
  private:
  double _internal_angular_velocity_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_angular_velocity_covariance() const;
  void _internal_add_angular_velocity_covariance(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_angular_velocity_covariance();
  public:
  double angular_velocity_covariance(int index) const;
  void set_angular_velocity_covariance(int index, double value);
  void add_angular_velocity_covariance(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      angular_velocity_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_angular_velocity_covariance();

  // repeated double linear_acceleration_covariance = 7;
  int linear_acceleration_covariance_size() const;
  private:
  int _internal_linear_acceleration_covariance_size() const;
  public:
  void clear_linear_acceleration_covariance();
  private:
  double _internal_linear_acceleration_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_linear_acceleration_covariance() const;
  void _internal_add_linear_acceleration_covariance(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_linear_acceleration_covariance();
  public:
  double linear_acceleration_covariance(int index) const;
  void set_linear_acceleration_covariance(int index, double value);
  void add_linear_acceleration_covariance(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      linear_acceleration_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_linear_acceleration_covariance();

  // .aimrt.protocols.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::aimrt::protocols::common::Header& header() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::common::Header* release_header();
  ::aimrt::protocols::common::Header* mutable_header();
  void set_allocated_header(::aimrt::protocols::common::Header* header);
  private:
  const ::aimrt::protocols::common::Header& _internal_header() const;
  ::aimrt::protocols::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::aimrt::protocols::common::Header* header);
  ::aimrt::protocols::common::Header* unsafe_arena_release_header();

  // .aimrt.protocols.geometry.Quaternion orientation = 2;
  bool has_orientation() const;
  private:
  bool _internal_has_orientation() const;
  public:
  void clear_orientation();
  const ::aimrt::protocols::geometry::Quaternion& orientation() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::geometry::Quaternion* release_orientation();
  ::aimrt::protocols::geometry::Quaternion* mutable_orientation();
  void set_allocated_orientation(::aimrt::protocols::geometry::Quaternion* orientation);
  private:
  const ::aimrt::protocols::geometry::Quaternion& _internal_orientation() const;
  ::aimrt::protocols::geometry::Quaternion* _internal_mutable_orientation();
  public:
  void unsafe_arena_set_allocated_orientation(
      ::aimrt::protocols::geometry::Quaternion* orientation);
  ::aimrt::protocols::geometry::Quaternion* unsafe_arena_release_orientation();

  // .aimrt.protocols.geometry.Vector3 angular_velocity = 4;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::aimrt::protocols::geometry::Vector3& angular_velocity() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::geometry::Vector3* release_angular_velocity();
  ::aimrt::protocols::geometry::Vector3* mutable_angular_velocity();
  void set_allocated_angular_velocity(::aimrt::protocols::geometry::Vector3* angular_velocity);
  private:
  const ::aimrt::protocols::geometry::Vector3& _internal_angular_velocity() const;
  ::aimrt::protocols::geometry::Vector3* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::aimrt::protocols::geometry::Vector3* angular_velocity);
  ::aimrt::protocols::geometry::Vector3* unsafe_arena_release_angular_velocity();

  // .aimrt.protocols.geometry.Vector3 linear_acceleration = 6;
  bool has_linear_acceleration() const;
  private:
  bool _internal_has_linear_acceleration() const;
  public:
  void clear_linear_acceleration();
  const ::aimrt::protocols::geometry::Vector3& linear_acceleration() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::geometry::Vector3* release_linear_acceleration();
  ::aimrt::protocols::geometry::Vector3* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::aimrt::protocols::geometry::Vector3* linear_acceleration);
  private:
  const ::aimrt::protocols::geometry::Vector3& _internal_linear_acceleration() const;
  ::aimrt::protocols::geometry::Vector3* _internal_mutable_linear_acceleration();
  public:
  void unsafe_arena_set_allocated_linear_acceleration(
      ::aimrt::protocols::geometry::Vector3* linear_acceleration);
  ::aimrt::protocols::geometry::Vector3* unsafe_arena_release_linear_acceleration();

  // @@protoc_insertion_point(class_scope:aimrt.protocols.sensor.ImuState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > orientation_covariance_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > angular_velocity_covariance_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > linear_acceleration_covariance_;
    ::aimrt::protocols::common::Header* header_;
    ::aimrt::protocols::geometry::Quaternion* orientation_;
    ::aimrt::protocols::geometry::Vector3* angular_velocity_;
    ::aimrt::protocols::geometry::Vector3* linear_acceleration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_imu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImuState

// .aimrt.protocols.common.Header header = 1;
inline bool ImuState::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool ImuState::has_header() const {
  return _internal_has_header();
}
inline const ::aimrt::protocols::common::Header& ImuState::_internal_header() const {
  const ::aimrt::protocols::common::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::common::Header&>(
      ::aimrt::protocols::common::_Header_default_instance_);
}
inline const ::aimrt::protocols::common::Header& ImuState::header() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.header)
  return _internal_header();
}
inline void ImuState::unsafe_arena_set_allocated_header(
    ::aimrt::protocols::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.ImuState.header)
}
inline ::aimrt::protocols::common::Header* ImuState::release_header() {
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::common::Header* ImuState::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.ImuState.header)
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::common::Header* ImuState::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::common::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::aimrt::protocols::common::Header* ImuState::mutable_header() {
  ::aimrt::protocols::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.ImuState.header)
  return _msg;
}
inline void ImuState::set_allocated_header(::aimrt::protocols::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.ImuState.header)
}

// .aimrt.protocols.geometry.Quaternion orientation = 2;
inline bool ImuState::_internal_has_orientation() const {
  return this != internal_default_instance() && _impl_.orientation_ != nullptr;
}
inline bool ImuState::has_orientation() const {
  return _internal_has_orientation();
}
inline const ::aimrt::protocols::geometry::Quaternion& ImuState::_internal_orientation() const {
  const ::aimrt::protocols::geometry::Quaternion* p = _impl_.orientation_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::geometry::Quaternion&>(
      ::aimrt::protocols::geometry::_Quaternion_default_instance_);
}
inline const ::aimrt::protocols::geometry::Quaternion& ImuState::orientation() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.orientation)
  return _internal_orientation();
}
inline void ImuState::unsafe_arena_set_allocated_orientation(
    ::aimrt::protocols::geometry::Quaternion* orientation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.orientation_);
  }
  _impl_.orientation_ = orientation;
  if (orientation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.ImuState.orientation)
}
inline ::aimrt::protocols::geometry::Quaternion* ImuState::release_orientation() {
  
  ::aimrt::protocols::geometry::Quaternion* temp = _impl_.orientation_;
  _impl_.orientation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::geometry::Quaternion* ImuState::unsafe_arena_release_orientation() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.ImuState.orientation)
  
  ::aimrt::protocols::geometry::Quaternion* temp = _impl_.orientation_;
  _impl_.orientation_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::geometry::Quaternion* ImuState::_internal_mutable_orientation() {
  
  if (_impl_.orientation_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::geometry::Quaternion>(GetArenaForAllocation());
    _impl_.orientation_ = p;
  }
  return _impl_.orientation_;
}
inline ::aimrt::protocols::geometry::Quaternion* ImuState::mutable_orientation() {
  ::aimrt::protocols::geometry::Quaternion* _msg = _internal_mutable_orientation();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.ImuState.orientation)
  return _msg;
}
inline void ImuState::set_allocated_orientation(::aimrt::protocols::geometry::Quaternion* orientation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.orientation_);
  }
  if (orientation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation));
    if (message_arena != submessage_arena) {
      orientation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, orientation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.orientation_ = orientation;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.ImuState.orientation)
}

// repeated double orientation_covariance = 3;
inline int ImuState::_internal_orientation_covariance_size() const {
  return _impl_.orientation_covariance_.size();
}
inline int ImuState::orientation_covariance_size() const {
  return _internal_orientation_covariance_size();
}
inline void ImuState::clear_orientation_covariance() {
  _impl_.orientation_covariance_.Clear();
}
inline double ImuState::_internal_orientation_covariance(int index) const {
  return _impl_.orientation_covariance_.Get(index);
}
inline double ImuState::orientation_covariance(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.orientation_covariance)
  return _internal_orientation_covariance(index);
}
inline void ImuState::set_orientation_covariance(int index, double value) {
  _impl_.orientation_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.ImuState.orientation_covariance)
}
inline void ImuState::_internal_add_orientation_covariance(double value) {
  _impl_.orientation_covariance_.Add(value);
}
inline void ImuState::add_orientation_covariance(double value) {
  _internal_add_orientation_covariance(value);
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.ImuState.orientation_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::_internal_orientation_covariance() const {
  return _impl_.orientation_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::orientation_covariance() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.ImuState.orientation_covariance)
  return _internal_orientation_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::_internal_mutable_orientation_covariance() {
  return &_impl_.orientation_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::mutable_orientation_covariance() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.ImuState.orientation_covariance)
  return _internal_mutable_orientation_covariance();
}

// .aimrt.protocols.geometry.Vector3 angular_velocity = 4;
inline bool ImuState::_internal_has_angular_velocity() const {
  return this != internal_default_instance() && _impl_.angular_velocity_ != nullptr;
}
inline bool ImuState::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline const ::aimrt::protocols::geometry::Vector3& ImuState::_internal_angular_velocity() const {
  const ::aimrt::protocols::geometry::Vector3* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::geometry::Vector3&>(
      ::aimrt::protocols::geometry::_Vector3_default_instance_);
}
inline const ::aimrt::protocols::geometry::Vector3& ImuState::angular_velocity() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.angular_velocity)
  return _internal_angular_velocity();
}
inline void ImuState::unsafe_arena_set_allocated_angular_velocity(
    ::aimrt::protocols::geometry::Vector3* angular_velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.ImuState.angular_velocity)
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::release_angular_velocity() {
  
  ::aimrt::protocols::geometry::Vector3* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.ImuState.angular_velocity)
  
  ::aimrt::protocols::geometry::Vector3* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::_internal_mutable_angular_velocity() {
  
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::geometry::Vector3>(GetArenaForAllocation());
    _impl_.angular_velocity_ = p;
  }
  return _impl_.angular_velocity_;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::mutable_angular_velocity() {
  ::aimrt::protocols::geometry::Vector3* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.ImuState.angular_velocity)
  return _msg;
}
inline void ImuState::set_allocated_angular_velocity(::aimrt::protocols::geometry::Vector3* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity));
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.ImuState.angular_velocity)
}

// repeated double angular_velocity_covariance = 5;
inline int ImuState::_internal_angular_velocity_covariance_size() const {
  return _impl_.angular_velocity_covariance_.size();
}
inline int ImuState::angular_velocity_covariance_size() const {
  return _internal_angular_velocity_covariance_size();
}
inline void ImuState::clear_angular_velocity_covariance() {
  _impl_.angular_velocity_covariance_.Clear();
}
inline double ImuState::_internal_angular_velocity_covariance(int index) const {
  return _impl_.angular_velocity_covariance_.Get(index);
}
inline double ImuState::angular_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.angular_velocity_covariance)
  return _internal_angular_velocity_covariance(index);
}
inline void ImuState::set_angular_velocity_covariance(int index, double value) {
  _impl_.angular_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.ImuState.angular_velocity_covariance)
}
inline void ImuState::_internal_add_angular_velocity_covariance(double value) {
  _impl_.angular_velocity_covariance_.Add(value);
}
inline void ImuState::add_angular_velocity_covariance(double value) {
  _internal_add_angular_velocity_covariance(value);
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.ImuState.angular_velocity_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::_internal_angular_velocity_covariance() const {
  return _impl_.angular_velocity_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::angular_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.ImuState.angular_velocity_covariance)
  return _internal_angular_velocity_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::_internal_mutable_angular_velocity_covariance() {
  return &_impl_.angular_velocity_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::mutable_angular_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.ImuState.angular_velocity_covariance)
  return _internal_mutable_angular_velocity_covariance();
}

// .aimrt.protocols.geometry.Vector3 linear_acceleration = 6;
inline bool ImuState::_internal_has_linear_acceleration() const {
  return this != internal_default_instance() && _impl_.linear_acceleration_ != nullptr;
}
inline bool ImuState::has_linear_acceleration() const {
  return _internal_has_linear_acceleration();
}
inline const ::aimrt::protocols::geometry::Vector3& ImuState::_internal_linear_acceleration() const {
  const ::aimrt::protocols::geometry::Vector3* p = _impl_.linear_acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::geometry::Vector3&>(
      ::aimrt::protocols::geometry::_Vector3_default_instance_);
}
inline const ::aimrt::protocols::geometry::Vector3& ImuState::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.linear_acceleration)
  return _internal_linear_acceleration();
}
inline void ImuState::unsafe_arena_set_allocated_linear_acceleration(
    ::aimrt::protocols::geometry::Vector3* linear_acceleration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.linear_acceleration_);
  }
  _impl_.linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.ImuState.linear_acceleration)
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::release_linear_acceleration() {
  
  ::aimrt::protocols::geometry::Vector3* temp = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::unsafe_arena_release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.ImuState.linear_acceleration)
  
  ::aimrt::protocols::geometry::Vector3* temp = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::_internal_mutable_linear_acceleration() {
  
  if (_impl_.linear_acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::geometry::Vector3>(GetArenaForAllocation());
    _impl_.linear_acceleration_ = p;
  }
  return _impl_.linear_acceleration_;
}
inline ::aimrt::protocols::geometry::Vector3* ImuState::mutable_linear_acceleration() {
  ::aimrt::protocols::geometry::Vector3* _msg = _internal_mutable_linear_acceleration();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.ImuState.linear_acceleration)
  return _msg;
}
inline void ImuState::set_allocated_linear_acceleration(::aimrt::protocols::geometry::Vector3* linear_acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.linear_acceleration_);
  }
  if (linear_acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration));
    if (message_arena != submessage_arena) {
      linear_acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_acceleration, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.linear_acceleration_ = linear_acceleration;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.ImuState.linear_acceleration)
}

// repeated double linear_acceleration_covariance = 7;
inline int ImuState::_internal_linear_acceleration_covariance_size() const {
  return _impl_.linear_acceleration_covariance_.size();
}
inline int ImuState::linear_acceleration_covariance_size() const {
  return _internal_linear_acceleration_covariance_size();
}
inline void ImuState::clear_linear_acceleration_covariance() {
  _impl_.linear_acceleration_covariance_.Clear();
}
inline double ImuState::_internal_linear_acceleration_covariance(int index) const {
  return _impl_.linear_acceleration_covariance_.Get(index);
}
inline double ImuState::linear_acceleration_covariance(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.ImuState.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance(index);
}
inline void ImuState::set_linear_acceleration_covariance(int index, double value) {
  _impl_.linear_acceleration_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.ImuState.linear_acceleration_covariance)
}
inline void ImuState::_internal_add_linear_acceleration_covariance(double value) {
  _impl_.linear_acceleration_covariance_.Add(value);
}
inline void ImuState::add_linear_acceleration_covariance(double value) {
  _internal_add_linear_acceleration_covariance(value);
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.ImuState.linear_acceleration_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::_internal_linear_acceleration_covariance() const {
  return _impl_.linear_acceleration_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
ImuState::linear_acceleration_covariance() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.ImuState.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::_internal_mutable_linear_acceleration_covariance() {
  return &_impl_.linear_acceleration_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
ImuState::mutable_linear_acceleration_covariance() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.ImuState.linear_acceleration_covariance)
  return _internal_mutable_linear_acceleration_covariance();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_imu_2eproto
