// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touch_sensor_state.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_touch_5fsensor_5fstate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_touch_5fsensor_5fstate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_touch_5fsensor_5fstate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_touch_5fsensor_5fstate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_touch_5fsensor_5fstate_2eproto;
namespace aimrt {
namespace protocols {
namespace sensor {
class TouchSensorState;
struct TouchSensorStateDefaultTypeInternal;
extern TouchSensorStateDefaultTypeInternal _TouchSensorState_default_instance_;
class TouchSensorStateArray;
struct TouchSensorStateArrayDefaultTypeInternal;
extern TouchSensorStateArrayDefaultTypeInternal _TouchSensorStateArray_default_instance_;
}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt
PROTOBUF_NAMESPACE_OPEN
template<> ::aimrt::protocols::sensor::TouchSensorState* Arena::CreateMaybeMessage<::aimrt::protocols::sensor::TouchSensorState>(Arena*);
template<> ::aimrt::protocols::sensor::TouchSensorStateArray* Arena::CreateMaybeMessage<::aimrt::protocols::sensor::TouchSensorStateArray>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aimrt {
namespace protocols {
namespace sensor {

// ===================================================================

class TouchSensorState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.sensor.TouchSensorState) */ {
 public:
  inline TouchSensorState() : TouchSensorState(nullptr) {}
  ~TouchSensorState() override;
  explicit PROTOBUF_CONSTEXPR TouchSensorState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TouchSensorState(const TouchSensorState& from);
  TouchSensorState(TouchSensorState&& from) noexcept
    : TouchSensorState() {
    *this = ::std::move(from);
  }

  inline TouchSensorState& operator=(const TouchSensorState& from) {
    CopyFrom(from);
    return *this;
  }
  inline TouchSensorState& operator=(TouchSensorState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TouchSensorState& default_instance() {
    return *internal_default_instance();
  }
  static inline const TouchSensorState* internal_default_instance() {
    return reinterpret_cast<const TouchSensorState*>(
               &_TouchSensorState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TouchSensorState& a, TouchSensorState& b) {
    a.Swap(&b);
  }
  inline void Swap(TouchSensorState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TouchSensorState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TouchSensorState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TouchSensorState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TouchSensorState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TouchSensorState& from) {
    TouchSensorState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TouchSensorState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.sensor.TouchSensorState";
  }
  protected:
  explicit TouchSensorState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPressureFieldNumber = 1,
  };
  // repeated int32 pressure = 1;
  int pressure_size() const;
  private:
  int _internal_pressure_size() const;
  public:
  void clear_pressure();
  private:
  int32_t _internal_pressure(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_pressure() const;
  void _internal_add_pressure(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_pressure();
  public:
  int32_t pressure(int index) const;
  void set_pressure(int index, int32_t value);
  void add_pressure(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      pressure() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_pressure();

  // @@protoc_insertion_point(class_scope:aimrt.protocols.sensor.TouchSensorState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > pressure_;
    mutable std::atomic<int> _pressure_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_touch_5fsensor_5fstate_2eproto;
};
// -------------------------------------------------------------------

class TouchSensorStateArray final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.sensor.TouchSensorStateArray) */ {
 public:
  inline TouchSensorStateArray() : TouchSensorStateArray(nullptr) {}
  ~TouchSensorStateArray() override;
  explicit PROTOBUF_CONSTEXPR TouchSensorStateArray(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TouchSensorStateArray(const TouchSensorStateArray& from);
  TouchSensorStateArray(TouchSensorStateArray&& from) noexcept
    : TouchSensorStateArray() {
    *this = ::std::move(from);
  }

  inline TouchSensorStateArray& operator=(const TouchSensorStateArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline TouchSensorStateArray& operator=(TouchSensorStateArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TouchSensorStateArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const TouchSensorStateArray* internal_default_instance() {
    return reinterpret_cast<const TouchSensorStateArray*>(
               &_TouchSensorStateArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TouchSensorStateArray& a, TouchSensorStateArray& b) {
    a.Swap(&b);
  }
  inline void Swap(TouchSensorStateArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TouchSensorStateArray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TouchSensorStateArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TouchSensorStateArray>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TouchSensorStateArray& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TouchSensorStateArray& from) {
    TouchSensorStateArray::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TouchSensorStateArray* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.sensor.TouchSensorStateArray";
  }
  protected:
  explicit TouchSensorStateArray(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNamesFieldNumber = 2,
    kStatesFieldNumber = 3,
    kHeaderFieldNumber = 1,
  };
  // repeated string names = 2;
  int names_size() const;
  private:
  int _internal_names_size() const;
  public:
  void clear_names();
  const std::string& names(int index) const;
  std::string* mutable_names(int index);
  void set_names(int index, const std::string& value);
  void set_names(int index, std::string&& value);
  void set_names(int index, const char* value);
  void set_names(int index, const char* value, size_t size);
  std::string* add_names();
  void add_names(const std::string& value);
  void add_names(std::string&& value);
  void add_names(const char* value);
  void add_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_names();
  private:
  const std::string& _internal_names(int index) const;
  std::string* _internal_add_names();
  public:

  // repeated .aimrt.protocols.sensor.TouchSensorState states = 3;
  int states_size() const;
  private:
  int _internal_states_size() const;
  public:
  void clear_states();
  ::aimrt::protocols::sensor::TouchSensorState* mutable_states(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::TouchSensorState >*
      mutable_states();
  private:
  const ::aimrt::protocols::sensor::TouchSensorState& _internal_states(int index) const;
  ::aimrt::protocols::sensor::TouchSensorState* _internal_add_states();
  public:
  const ::aimrt::protocols::sensor::TouchSensorState& states(int index) const;
  ::aimrt::protocols::sensor::TouchSensorState* add_states();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::TouchSensorState >&
      states() const;

  // .aimrt.protocols.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::aimrt::protocols::common::Header& header() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::common::Header* release_header();
  ::aimrt::protocols::common::Header* mutable_header();
  void set_allocated_header(::aimrt::protocols::common::Header* header);
  private:
  const ::aimrt::protocols::common::Header& _internal_header() const;
  ::aimrt::protocols::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::aimrt::protocols::common::Header* header);
  ::aimrt::protocols::common::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:aimrt.protocols.sensor.TouchSensorStateArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> names_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::TouchSensorState > states_;
    ::aimrt::protocols::common::Header* header_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_touch_5fsensor_5fstate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TouchSensorState

// repeated int32 pressure = 1;
inline int TouchSensorState::_internal_pressure_size() const {
  return _impl_.pressure_.size();
}
inline int TouchSensorState::pressure_size() const {
  return _internal_pressure_size();
}
inline void TouchSensorState::clear_pressure() {
  _impl_.pressure_.Clear();
}
inline int32_t TouchSensorState::_internal_pressure(int index) const {
  return _impl_.pressure_.Get(index);
}
inline int32_t TouchSensorState::pressure(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.TouchSensorState.pressure)
  return _internal_pressure(index);
}
inline void TouchSensorState::set_pressure(int index, int32_t value) {
  _impl_.pressure_.Set(index, value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.TouchSensorState.pressure)
}
inline void TouchSensorState::_internal_add_pressure(int32_t value) {
  _impl_.pressure_.Add(value);
}
inline void TouchSensorState::add_pressure(int32_t value) {
  _internal_add_pressure(value);
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.TouchSensorState.pressure)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TouchSensorState::_internal_pressure() const {
  return _impl_.pressure_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
TouchSensorState::pressure() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.TouchSensorState.pressure)
  return _internal_pressure();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TouchSensorState::_internal_mutable_pressure() {
  return &_impl_.pressure_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
TouchSensorState::mutable_pressure() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.TouchSensorState.pressure)
  return _internal_mutable_pressure();
}

// -------------------------------------------------------------------

// TouchSensorStateArray

// .aimrt.protocols.common.Header header = 1;
inline bool TouchSensorStateArray::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool TouchSensorStateArray::has_header() const {
  return _internal_has_header();
}
inline const ::aimrt::protocols::common::Header& TouchSensorStateArray::_internal_header() const {
  const ::aimrt::protocols::common::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::common::Header&>(
      ::aimrt::protocols::common::_Header_default_instance_);
}
inline const ::aimrt::protocols::common::Header& TouchSensorStateArray::header() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.TouchSensorStateArray.header)
  return _internal_header();
}
inline void TouchSensorStateArray::unsafe_arena_set_allocated_header(
    ::aimrt::protocols::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.sensor.TouchSensorStateArray.header)
}
inline ::aimrt::protocols::common::Header* TouchSensorStateArray::release_header() {
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::common::Header* TouchSensorStateArray::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.sensor.TouchSensorStateArray.header)
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::common::Header* TouchSensorStateArray::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::common::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::aimrt::protocols::common::Header* TouchSensorStateArray::mutable_header() {
  ::aimrt::protocols::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.TouchSensorStateArray.header)
  return _msg;
}
inline void TouchSensorStateArray::set_allocated_header(::aimrt::protocols::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.sensor.TouchSensorStateArray.header)
}

// repeated string names = 2;
inline int TouchSensorStateArray::_internal_names_size() const {
  return _impl_.names_.size();
}
inline int TouchSensorStateArray::names_size() const {
  return _internal_names_size();
}
inline void TouchSensorStateArray::clear_names() {
  _impl_.names_.Clear();
}
inline std::string* TouchSensorStateArray::add_names() {
  std::string* _s = _internal_add_names();
  // @@protoc_insertion_point(field_add_mutable:aimrt.protocols.sensor.TouchSensorStateArray.names)
  return _s;
}
inline const std::string& TouchSensorStateArray::_internal_names(int index) const {
  return _impl_.names_.Get(index);
}
inline const std::string& TouchSensorStateArray::names(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.TouchSensorStateArray.names)
  return _internal_names(index);
}
inline std::string* TouchSensorStateArray::mutable_names(int index) {
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.TouchSensorStateArray.names)
  return _impl_.names_.Mutable(index);
}
inline void TouchSensorStateArray::set_names(int index, const std::string& value) {
  _impl_.names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::set_names(int index, std::string&& value) {
  _impl_.names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::set_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::set_names(int index, const char* value, size_t size) {
  _impl_.names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline std::string* TouchSensorStateArray::_internal_add_names() {
  return _impl_.names_.Add();
}
inline void TouchSensorStateArray::add_names(const std::string& value) {
  _impl_.names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::add_names(std::string&& value) {
  _impl_.names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::add_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline void TouchSensorStateArray::add_names(const char* value, size_t size) {
  _impl_.names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aimrt.protocols.sensor.TouchSensorStateArray.names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TouchSensorStateArray::names() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.TouchSensorStateArray.names)
  return _impl_.names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TouchSensorStateArray::mutable_names() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.TouchSensorStateArray.names)
  return &_impl_.names_;
}

// repeated .aimrt.protocols.sensor.TouchSensorState states = 3;
inline int TouchSensorStateArray::_internal_states_size() const {
  return _impl_.states_.size();
}
inline int TouchSensorStateArray::states_size() const {
  return _internal_states_size();
}
inline void TouchSensorStateArray::clear_states() {
  _impl_.states_.Clear();
}
inline ::aimrt::protocols::sensor::TouchSensorState* TouchSensorStateArray::mutable_states(int index) {
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.sensor.TouchSensorStateArray.states)
  return _impl_.states_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::TouchSensorState >*
TouchSensorStateArray::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:aimrt.protocols.sensor.TouchSensorStateArray.states)
  return &_impl_.states_;
}
inline const ::aimrt::protocols::sensor::TouchSensorState& TouchSensorStateArray::_internal_states(int index) const {
  return _impl_.states_.Get(index);
}
inline const ::aimrt::protocols::sensor::TouchSensorState& TouchSensorStateArray::states(int index) const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.sensor.TouchSensorStateArray.states)
  return _internal_states(index);
}
inline ::aimrt::protocols::sensor::TouchSensorState* TouchSensorStateArray::_internal_add_states() {
  return _impl_.states_.Add();
}
inline ::aimrt::protocols::sensor::TouchSensorState* TouchSensorStateArray::add_states() {
  ::aimrt::protocols::sensor::TouchSensorState* _add = _internal_add_states();
  // @@protoc_insertion_point(field_add:aimrt.protocols.sensor.TouchSensorStateArray.states)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aimrt::protocols::sensor::TouchSensorState >&
TouchSensorStateArray::states() const {
  // @@protoc_insertion_point(field_list:aimrt.protocols.sensor.TouchSensorStateArray.states)
  return _impl_.states_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor
}  // namespace protocols
}  // namespace aimrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_touch_5fsensor_5fstate_2eproto
