// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_module_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_module_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_module_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_module_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_module_2eproto;
namespace aimrt {
namespace protocols {
namespace common {
class ModuleException;
struct ModuleExceptionDefaultTypeInternal;
extern ModuleExceptionDefaultTypeInternal _ModuleException_default_instance_;
class ModuleException_ContextEntry_DoNotUse;
struct ModuleException_ContextEntry_DoNotUseDefaultTypeInternal;
extern ModuleException_ContextEntry_DoNotUseDefaultTypeInternal _ModuleException_ContextEntry_DoNotUse_default_instance_;
class ModuleStatus;
struct ModuleStatusDefaultTypeInternal;
extern ModuleStatusDefaultTypeInternal _ModuleStatus_default_instance_;
class ModuleStatus_Status;
struct ModuleStatus_StatusDefaultTypeInternal;
extern ModuleStatus_StatusDefaultTypeInternal _ModuleStatus_Status_default_instance_;
class ModuleStatus_StatusMapEntry_DoNotUse;
struct ModuleStatus_StatusMapEntry_DoNotUseDefaultTypeInternal;
extern ModuleStatus_StatusMapEntry_DoNotUseDefaultTypeInternal _ModuleStatus_StatusMapEntry_DoNotUse_default_instance_;
}  // namespace common
}  // namespace protocols
}  // namespace aimrt
PROTOBUF_NAMESPACE_OPEN
template<> ::aimrt::protocols::common::ModuleException* Arena::CreateMaybeMessage<::aimrt::protocols::common::ModuleException>(Arena*);
template<> ::aimrt::protocols::common::ModuleException_ContextEntry_DoNotUse* Arena::CreateMaybeMessage<::aimrt::protocols::common::ModuleException_ContextEntry_DoNotUse>(Arena*);
template<> ::aimrt::protocols::common::ModuleStatus* Arena::CreateMaybeMessage<::aimrt::protocols::common::ModuleStatus>(Arena*);
template<> ::aimrt::protocols::common::ModuleStatus_Status* Arena::CreateMaybeMessage<::aimrt::protocols::common::ModuleStatus_Status>(Arena*);
template<> ::aimrt::protocols::common::ModuleStatus_StatusMapEntry_DoNotUse* Arena::CreateMaybeMessage<::aimrt::protocols::common::ModuleStatus_StatusMapEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aimrt {
namespace protocols {
namespace common {

// ===================================================================

class ModuleStatus_Status final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.common.ModuleStatus.Status) */ {
 public:
  inline ModuleStatus_Status() : ModuleStatus_Status(nullptr) {}
  ~ModuleStatus_Status() override;
  explicit PROTOBUF_CONSTEXPR ModuleStatus_Status(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModuleStatus_Status(const ModuleStatus_Status& from);
  ModuleStatus_Status(ModuleStatus_Status&& from) noexcept
    : ModuleStatus_Status() {
    *this = ::std::move(from);
  }

  inline ModuleStatus_Status& operator=(const ModuleStatus_Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModuleStatus_Status& operator=(ModuleStatus_Status&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModuleStatus_Status& default_instance() {
    return *internal_default_instance();
  }
  enum ValueCase {
    kBoolValue = 1,
    kIntValue = 2,
    kDoubleValue = 3,
    kStringValue = 4,
    kBytesValue = 5,
    VALUE_NOT_SET = 0,
  };

  static inline const ModuleStatus_Status* internal_default_instance() {
    return reinterpret_cast<const ModuleStatus_Status*>(
               &_ModuleStatus_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ModuleStatus_Status& a, ModuleStatus_Status& b) {
    a.Swap(&b);
  }
  inline void Swap(ModuleStatus_Status* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModuleStatus_Status* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModuleStatus_Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModuleStatus_Status>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModuleStatus_Status& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModuleStatus_Status& from) {
    ModuleStatus_Status::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleStatus_Status* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.common.ModuleStatus.Status";
  }
  protected:
  explicit ModuleStatus_Status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBoolValueFieldNumber = 1,
    kIntValueFieldNumber = 2,
    kDoubleValueFieldNumber = 3,
    kStringValueFieldNumber = 4,
    kBytesValueFieldNumber = 5,
  };
  // bool bool_value = 1;
  bool has_bool_value() const;
  private:
  bool _internal_has_bool_value() const;
  public:
  void clear_bool_value();
  bool bool_value() const;
  void set_bool_value(bool value);
  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);
  public:

  // int64 int_value = 2;
  bool has_int_value() const;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  int64_t int_value() const;
  void set_int_value(int64_t value);
  private:
  int64_t _internal_int_value() const;
  void _internal_set_int_value(int64_t value);
  public:

  // double double_value = 3;
  bool has_double_value() const;
  private:
  bool _internal_has_double_value() const;
  public:
  void clear_double_value();
  double double_value() const;
  void set_double_value(double value);
  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);
  public:

  // string string_value = 4;
  bool has_string_value() const;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_value();
  PROTOBUF_NODISCARD std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  // bytes bytes_value = 5;
  bool has_bytes_value() const;
  private:
  bool _internal_has_bytes_value() const;
  public:
  void clear_bytes_value();
  const std::string& bytes_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bytes_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bytes_value();
  PROTOBUF_NODISCARD std::string* release_bytes_value();
  void set_allocated_bytes_value(std::string* bytes_value);
  private:
  const std::string& _internal_bytes_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bytes_value(const std::string& value);
  std::string* _internal_mutable_bytes_value();
  public:

  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:aimrt.protocols.common.ModuleStatus.Status)
 private:
  class _Internal;
  void set_has_bool_value();
  void set_has_int_value();
  void set_has_double_value();
  void set_has_string_value();
  void set_has_bytes_value();

  inline bool has_value() const;
  inline void clear_has_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ValueUnion {
      constexpr ValueUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      bool bool_value_;
      int64_t int_value_;
      double double_value_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytes_value_;
    } value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_module_2eproto;
};
// -------------------------------------------------------------------

class ModuleStatus_StatusMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModuleStatus_StatusMapEntry_DoNotUse, 
    std::string, ::aimrt::protocols::common::ModuleStatus_Status,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModuleStatus_StatusMapEntry_DoNotUse, 
    std::string, ::aimrt::protocols::common::ModuleStatus_Status,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  ModuleStatus_StatusMapEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR ModuleStatus_StatusMapEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit ModuleStatus_StatusMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ModuleStatus_StatusMapEntry_DoNotUse& other);
  static const ModuleStatus_StatusMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ModuleStatus_StatusMapEntry_DoNotUse*>(&_ModuleStatus_StatusMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "aimrt.protocols.common.ModuleStatus.StatusMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_module_2eproto;
};

// -------------------------------------------------------------------

class ModuleStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.common.ModuleStatus) */ {
 public:
  inline ModuleStatus() : ModuleStatus(nullptr) {}
  ~ModuleStatus() override;
  explicit PROTOBUF_CONSTEXPR ModuleStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModuleStatus(const ModuleStatus& from);
  ModuleStatus(ModuleStatus&& from) noexcept
    : ModuleStatus() {
    *this = ::std::move(from);
  }

  inline ModuleStatus& operator=(const ModuleStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModuleStatus& operator=(ModuleStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModuleStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModuleStatus* internal_default_instance() {
    return reinterpret_cast<const ModuleStatus*>(
               &_ModuleStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ModuleStatus& a, ModuleStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(ModuleStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModuleStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModuleStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModuleStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModuleStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModuleStatus& from) {
    ModuleStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.common.ModuleStatus";
  }
  protected:
  explicit ModuleStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ModuleStatus_Status Status;

  // accessors -------------------------------------------------------

  enum : int {
    kStatusMapFieldNumber = 3,
    kFromFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // map<string, .aimrt.protocols.common.ModuleStatus.Status> status_map = 3;
  int status_map_size() const;
  private:
  int _internal_status_map_size() const;
  public:
  void clear_status_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >&
      _internal_status_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >*
      _internal_mutable_status_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >&
      status_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >*
      mutable_status_map();

  // string from = 2;
  void clear_from();
  const std::string& from() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_from(ArgT0&& arg0, ArgT... args);
  std::string* mutable_from();
  PROTOBUF_NODISCARD std::string* release_from();
  void set_allocated_from(std::string* from);
  private:
  const std::string& _internal_from() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_from(const std::string& value);
  std::string* _internal_mutable_from();
  public:

  // .aimrt.protocols.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::aimrt::protocols::common::Header& header() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::common::Header* release_header();
  ::aimrt::protocols::common::Header* mutable_header();
  void set_allocated_header(::aimrt::protocols::common::Header* header);
  private:
  const ::aimrt::protocols::common::Header& _internal_header() const;
  ::aimrt::protocols::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::aimrt::protocols::common::Header* header);
  ::aimrt::protocols::common::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:aimrt.protocols.common.ModuleStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        ModuleStatus_StatusMapEntry_DoNotUse,
        std::string, ::aimrt::protocols::common::ModuleStatus_Status,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> status_map_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr from_;
    ::aimrt::protocols::common::Header* header_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_module_2eproto;
};
// -------------------------------------------------------------------

class ModuleException_ContextEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModuleException_ContextEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModuleException_ContextEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  ModuleException_ContextEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR ModuleException_ContextEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit ModuleException_ContextEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ModuleException_ContextEntry_DoNotUse& other);
  static const ModuleException_ContextEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ModuleException_ContextEntry_DoNotUse*>(&_ModuleException_ContextEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "aimrt.protocols.common.ModuleException.ContextEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "aimrt.protocols.common.ModuleException.ContextEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_module_2eproto;
};

// -------------------------------------------------------------------

class ModuleException final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.common.ModuleException) */ {
 public:
  inline ModuleException() : ModuleException(nullptr) {}
  ~ModuleException() override;
  explicit PROTOBUF_CONSTEXPR ModuleException(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModuleException(const ModuleException& from);
  ModuleException(ModuleException&& from) noexcept
    : ModuleException() {
    *this = ::std::move(from);
  }

  inline ModuleException& operator=(const ModuleException& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModuleException& operator=(ModuleException&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModuleException& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModuleException* internal_default_instance() {
    return reinterpret_cast<const ModuleException*>(
               &_ModuleException_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ModuleException& a, ModuleException& b) {
    a.Swap(&b);
  }
  inline void Swap(ModuleException* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModuleException* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModuleException* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModuleException>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModuleException& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModuleException& from) {
    ModuleException::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleException* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.common.ModuleException";
  }
  protected:
  explicit ModuleException(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kContextFieldNumber = 5,
    kFromFieldNumber = 2,
    kMsgFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kCodeFieldNumber = 3,
  };
  // map<string, string> context = 5;
  int context_size() const;
  private:
  int _internal_context_size() const;
  public:
  void clear_context();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_context() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_context();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      context() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_context();

  // string from = 2;
  void clear_from();
  const std::string& from() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_from(ArgT0&& arg0, ArgT... args);
  std::string* mutable_from();
  PROTOBUF_NODISCARD std::string* release_from();
  void set_allocated_from(std::string* from);
  private:
  const std::string& _internal_from() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_from(const std::string& value);
  std::string* _internal_mutable_from();
  public:

  // string msg = 4;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .aimrt.protocols.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::aimrt::protocols::common::Header& header() const;
  PROTOBUF_NODISCARD ::aimrt::protocols::common::Header* release_header();
  ::aimrt::protocols::common::Header* mutable_header();
  void set_allocated_header(::aimrt::protocols::common::Header* header);
  private:
  const ::aimrt::protocols::common::Header& _internal_header() const;
  ::aimrt::protocols::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::aimrt::protocols::common::Header* header);
  ::aimrt::protocols::common::Header* unsafe_arena_release_header();

  // int64 code = 3;
  void clear_code();
  int64_t code() const;
  void set_code(int64_t value);
  private:
  int64_t _internal_code() const;
  void _internal_set_code(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.common.ModuleException)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        ModuleException_ContextEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> context_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr from_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    ::aimrt::protocols::common::Header* header_;
    int64_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_module_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ModuleStatus_Status

// bool bool_value = 1;
inline bool ModuleStatus_Status::_internal_has_bool_value() const {
  return value_case() == kBoolValue;
}
inline bool ModuleStatus_Status::has_bool_value() const {
  return _internal_has_bool_value();
}
inline void ModuleStatus_Status::set_has_bool_value() {
  _impl_._oneof_case_[0] = kBoolValue;
}
inline void ModuleStatus_Status::clear_bool_value() {
  if (_internal_has_bool_value()) {
    _impl_.value_.bool_value_ = false;
    clear_has_value();
  }
}
inline bool ModuleStatus_Status::_internal_bool_value() const {
  if (_internal_has_bool_value()) {
    return _impl_.value_.bool_value_;
  }
  return false;
}
inline void ModuleStatus_Status::_internal_set_bool_value(bool value) {
  if (!_internal_has_bool_value()) {
    clear_value();
    set_has_bool_value();
  }
  _impl_.value_.bool_value_ = value;
}
inline bool ModuleStatus_Status::bool_value() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.Status.bool_value)
  return _internal_bool_value();
}
inline void ModuleStatus_Status::set_bool_value(bool value) {
  _internal_set_bool_value(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.Status.bool_value)
}

// int64 int_value = 2;
inline bool ModuleStatus_Status::_internal_has_int_value() const {
  return value_case() == kIntValue;
}
inline bool ModuleStatus_Status::has_int_value() const {
  return _internal_has_int_value();
}
inline void ModuleStatus_Status::set_has_int_value() {
  _impl_._oneof_case_[0] = kIntValue;
}
inline void ModuleStatus_Status::clear_int_value() {
  if (_internal_has_int_value()) {
    _impl_.value_.int_value_ = int64_t{0};
    clear_has_value();
  }
}
inline int64_t ModuleStatus_Status::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return _impl_.value_.int_value_;
  }
  return int64_t{0};
}
inline void ModuleStatus_Status::_internal_set_int_value(int64_t value) {
  if (!_internal_has_int_value()) {
    clear_value();
    set_has_int_value();
  }
  _impl_.value_.int_value_ = value;
}
inline int64_t ModuleStatus_Status::int_value() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.Status.int_value)
  return _internal_int_value();
}
inline void ModuleStatus_Status::set_int_value(int64_t value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.Status.int_value)
}

// double double_value = 3;
inline bool ModuleStatus_Status::_internal_has_double_value() const {
  return value_case() == kDoubleValue;
}
inline bool ModuleStatus_Status::has_double_value() const {
  return _internal_has_double_value();
}
inline void ModuleStatus_Status::set_has_double_value() {
  _impl_._oneof_case_[0] = kDoubleValue;
}
inline void ModuleStatus_Status::clear_double_value() {
  if (_internal_has_double_value()) {
    _impl_.value_.double_value_ = 0;
    clear_has_value();
  }
}
inline double ModuleStatus_Status::_internal_double_value() const {
  if (_internal_has_double_value()) {
    return _impl_.value_.double_value_;
  }
  return 0;
}
inline void ModuleStatus_Status::_internal_set_double_value(double value) {
  if (!_internal_has_double_value()) {
    clear_value();
    set_has_double_value();
  }
  _impl_.value_.double_value_ = value;
}
inline double ModuleStatus_Status::double_value() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.Status.double_value)
  return _internal_double_value();
}
inline void ModuleStatus_Status::set_double_value(double value) {
  _internal_set_double_value(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.Status.double_value)
}

// string string_value = 4;
inline bool ModuleStatus_Status::_internal_has_string_value() const {
  return value_case() == kStringValue;
}
inline bool ModuleStatus_Status::has_string_value() const {
  return _internal_has_string_value();
}
inline void ModuleStatus_Status::set_has_string_value() {
  _impl_._oneof_case_[0] = kStringValue;
}
inline void ModuleStatus_Status::clear_string_value() {
  if (_internal_has_string_value()) {
    _impl_.value_.string_value_.Destroy();
    clear_has_value();
  }
}
inline const std::string& ModuleStatus_Status::string_value() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.Status.string_value)
  return _internal_string_value();
}
template <typename ArgT0, typename... ArgT>
inline void ModuleStatus_Status::set_string_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.Status.string_value)
}
inline std::string* ModuleStatus_Status::mutable_string_value() {
  std::string* _s = _internal_mutable_string_value();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleStatus.Status.string_value)
  return _s;
}
inline const std::string& ModuleStatus_Status::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return _impl_.value_.string_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ModuleStatus_Status::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set(value, GetArenaForAllocation());
}
inline std::string* ModuleStatus_Status::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  return _impl_.value_.string_value_.Mutable(      GetArenaForAllocation());
}
inline std::string* ModuleStatus_Status::release_string_value() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleStatus.Status.string_value)
  if (_internal_has_string_value()) {
    clear_has_value();
    return _impl_.value_.string_value_.Release();
  } else {
    return nullptr;
  }
}
inline void ModuleStatus_Status::set_allocated_string_value(std::string* string_value) {
  if (has_value()) {
    clear_value();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    _impl_.value_.string_value_.InitAllocated(string_value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleStatus.Status.string_value)
}

// bytes bytes_value = 5;
inline bool ModuleStatus_Status::_internal_has_bytes_value() const {
  return value_case() == kBytesValue;
}
inline bool ModuleStatus_Status::has_bytes_value() const {
  return _internal_has_bytes_value();
}
inline void ModuleStatus_Status::set_has_bytes_value() {
  _impl_._oneof_case_[0] = kBytesValue;
}
inline void ModuleStatus_Status::clear_bytes_value() {
  if (_internal_has_bytes_value()) {
    _impl_.value_.bytes_value_.Destroy();
    clear_has_value();
  }
}
inline const std::string& ModuleStatus_Status::bytes_value() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.Status.bytes_value)
  return _internal_bytes_value();
}
template <typename ArgT0, typename... ArgT>
inline void ModuleStatus_Status::set_bytes_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    _impl_.value_.bytes_value_.InitDefault();
  }
  _impl_.value_.bytes_value_.SetBytes( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.Status.bytes_value)
}
inline std::string* ModuleStatus_Status::mutable_bytes_value() {
  std::string* _s = _internal_mutable_bytes_value();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleStatus.Status.bytes_value)
  return _s;
}
inline const std::string& ModuleStatus_Status::_internal_bytes_value() const {
  if (_internal_has_bytes_value()) {
    return _impl_.value_.bytes_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ModuleStatus_Status::_internal_set_bytes_value(const std::string& value) {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    _impl_.value_.bytes_value_.InitDefault();
  }
  _impl_.value_.bytes_value_.Set(value, GetArenaForAllocation());
}
inline std::string* ModuleStatus_Status::_internal_mutable_bytes_value() {
  if (!_internal_has_bytes_value()) {
    clear_value();
    set_has_bytes_value();
    _impl_.value_.bytes_value_.InitDefault();
  }
  return _impl_.value_.bytes_value_.Mutable(      GetArenaForAllocation());
}
inline std::string* ModuleStatus_Status::release_bytes_value() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleStatus.Status.bytes_value)
  if (_internal_has_bytes_value()) {
    clear_has_value();
    return _impl_.value_.bytes_value_.Release();
  } else {
    return nullptr;
  }
}
inline void ModuleStatus_Status::set_allocated_bytes_value(std::string* bytes_value) {
  if (has_value()) {
    clear_value();
  }
  if (bytes_value != nullptr) {
    set_has_bytes_value();
    _impl_.value_.bytes_value_.InitAllocated(bytes_value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleStatus.Status.bytes_value)
}

inline bool ModuleStatus_Status::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void ModuleStatus_Status::clear_has_value() {
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}
inline ModuleStatus_Status::ValueCase ModuleStatus_Status::value_case() const {
  return ModuleStatus_Status::ValueCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ModuleStatus

// .aimrt.protocols.common.Header header = 1;
inline bool ModuleStatus::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool ModuleStatus::has_header() const {
  return _internal_has_header();
}
inline const ::aimrt::protocols::common::Header& ModuleStatus::_internal_header() const {
  const ::aimrt::protocols::common::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::common::Header&>(
      ::aimrt::protocols::common::_Header_default_instance_);
}
inline const ::aimrt::protocols::common::Header& ModuleStatus::header() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.header)
  return _internal_header();
}
inline void ModuleStatus::unsafe_arena_set_allocated_header(
    ::aimrt::protocols::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.common.ModuleStatus.header)
}
inline ::aimrt::protocols::common::Header* ModuleStatus::release_header() {
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::common::Header* ModuleStatus::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleStatus.header)
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::common::Header* ModuleStatus::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::common::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::aimrt::protocols::common::Header* ModuleStatus::mutable_header() {
  ::aimrt::protocols::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleStatus.header)
  return _msg;
}
inline void ModuleStatus::set_allocated_header(::aimrt::protocols::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleStatus.header)
}

// string from = 2;
inline void ModuleStatus::clear_from() {
  _impl_.from_.ClearToEmpty();
}
inline const std::string& ModuleStatus::from() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleStatus.from)
  return _internal_from();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ModuleStatus::set_from(ArgT0&& arg0, ArgT... args) {
 
 _impl_.from_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleStatus.from)
}
inline std::string* ModuleStatus::mutable_from() {
  std::string* _s = _internal_mutable_from();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleStatus.from)
  return _s;
}
inline const std::string& ModuleStatus::_internal_from() const {
  return _impl_.from_.Get();
}
inline void ModuleStatus::_internal_set_from(const std::string& value) {
  
  _impl_.from_.Set(value, GetArenaForAllocation());
}
inline std::string* ModuleStatus::_internal_mutable_from() {
  
  return _impl_.from_.Mutable(GetArenaForAllocation());
}
inline std::string* ModuleStatus::release_from() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleStatus.from)
  return _impl_.from_.Release();
}
inline void ModuleStatus::set_allocated_from(std::string* from) {
  if (from != nullptr) {
    
  } else {
    
  }
  _impl_.from_.SetAllocated(from, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.from_.IsDefault()) {
    _impl_.from_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleStatus.from)
}

// map<string, .aimrt.protocols.common.ModuleStatus.Status> status_map = 3;
inline int ModuleStatus::_internal_status_map_size() const {
  return _impl_.status_map_.size();
}
inline int ModuleStatus::status_map_size() const {
  return _internal_status_map_size();
}
inline void ModuleStatus::clear_status_map() {
  _impl_.status_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >&
ModuleStatus::_internal_status_map() const {
  return _impl_.status_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >&
ModuleStatus::status_map() const {
  // @@protoc_insertion_point(field_map:aimrt.protocols.common.ModuleStatus.status_map)
  return _internal_status_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >*
ModuleStatus::_internal_mutable_status_map() {
  return _impl_.status_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::aimrt::protocols::common::ModuleStatus_Status >*
ModuleStatus::mutable_status_map() {
  // @@protoc_insertion_point(field_mutable_map:aimrt.protocols.common.ModuleStatus.status_map)
  return _internal_mutable_status_map();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ModuleException

// .aimrt.protocols.common.Header header = 1;
inline bool ModuleException::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool ModuleException::has_header() const {
  return _internal_has_header();
}
inline const ::aimrt::protocols::common::Header& ModuleException::_internal_header() const {
  const ::aimrt::protocols::common::Header* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::aimrt::protocols::common::Header&>(
      ::aimrt::protocols::common::_Header_default_instance_);
}
inline const ::aimrt::protocols::common::Header& ModuleException::header() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleException.header)
  return _internal_header();
}
inline void ModuleException::unsafe_arena_set_allocated_header(
    ::aimrt::protocols::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aimrt.protocols.common.ModuleException.header)
}
inline ::aimrt::protocols::common::Header* ModuleException::release_header() {
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aimrt::protocols::common::Header* ModuleException::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleException.header)
  
  ::aimrt::protocols::common::Header* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::aimrt::protocols::common::Header* ModuleException::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::aimrt::protocols::common::Header>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::aimrt::protocols::common::Header* ModuleException::mutable_header() {
  ::aimrt::protocols::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleException.header)
  return _msg;
}
inline void ModuleException::set_allocated_header(::aimrt::protocols::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleException.header)
}

// string from = 2;
inline void ModuleException::clear_from() {
  _impl_.from_.ClearToEmpty();
}
inline const std::string& ModuleException::from() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleException.from)
  return _internal_from();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ModuleException::set_from(ArgT0&& arg0, ArgT... args) {
 
 _impl_.from_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleException.from)
}
inline std::string* ModuleException::mutable_from() {
  std::string* _s = _internal_mutable_from();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleException.from)
  return _s;
}
inline const std::string& ModuleException::_internal_from() const {
  return _impl_.from_.Get();
}
inline void ModuleException::_internal_set_from(const std::string& value) {
  
  _impl_.from_.Set(value, GetArenaForAllocation());
}
inline std::string* ModuleException::_internal_mutable_from() {
  
  return _impl_.from_.Mutable(GetArenaForAllocation());
}
inline std::string* ModuleException::release_from() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleException.from)
  return _impl_.from_.Release();
}
inline void ModuleException::set_allocated_from(std::string* from) {
  if (from != nullptr) {
    
  } else {
    
  }
  _impl_.from_.SetAllocated(from, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.from_.IsDefault()) {
    _impl_.from_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleException.from)
}

// int64 code = 3;
inline void ModuleException::clear_code() {
  _impl_.code_ = int64_t{0};
}
inline int64_t ModuleException::_internal_code() const {
  return _impl_.code_;
}
inline int64_t ModuleException::code() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleException.code)
  return _internal_code();
}
inline void ModuleException::_internal_set_code(int64_t value) {
  
  _impl_.code_ = value;
}
inline void ModuleException::set_code(int64_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleException.code)
}

// string msg = 4;
inline void ModuleException::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& ModuleException::msg() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.common.ModuleException.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ModuleException::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.common.ModuleException.msg)
}
inline std::string* ModuleException::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.common.ModuleException.msg)
  return _s;
}
inline const std::string& ModuleException::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void ModuleException::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* ModuleException::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* ModuleException::release_msg() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.common.ModuleException.msg)
  return _impl_.msg_.Release();
}
inline void ModuleException::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.common.ModuleException.msg)
}

// map<string, string> context = 5;
inline int ModuleException::_internal_context_size() const {
  return _impl_.context_.size();
}
inline int ModuleException::context_size() const {
  return _internal_context_size();
}
inline void ModuleException::clear_context() {
  _impl_.context_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
ModuleException::_internal_context() const {
  return _impl_.context_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
ModuleException::context() const {
  // @@protoc_insertion_point(field_map:aimrt.protocols.common.ModuleException.context)
  return _internal_context();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
ModuleException::_internal_mutable_context() {
  return _impl_.context_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
ModuleException::mutable_context() {
  // @@protoc_insertion_point(field_mutable_map:aimrt.protocols.common.ModuleException.context)
  return _internal_mutable_context();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols
}  // namespace aimrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_module_2eproto
