/**
 * @file RosRpcWrapper.aimrt_rpc.srv.h
 * @brief This file was generated by ros2-aimrt_rpc-gen-code-tool, do not edit it!!!
 */
#pragma once

#include <future>

#include "aimrt_module_cpp_interface/rpc/rpc_handle.h"
#include "aimrt_module_cpp_interface/rpc/rpc_status.h"
#include "aimrt_module_cpp_interface/util/version.h"
#include "aimrt_module_cpp_interface/co/task.h"
#include "aimrt_module_cpp_interface/context/context.h"

#include "aimrt_module_cpp_interface.h"

#include "ros2_plugin_proto/srv/ros_rpc_wrapper.hpp"

static_assert(1000000 <= AIMRT_RUNTIME_VERSION_INT,
              "AIMRT_RUNTIME_VERSION is older than generated code version 1.0.0");
static_assert(AIMRT_MIN_GENCODE_VERSION_INT <= 1000000,
              "AIMRT_MIN_GENCODE_VERSION is greater than generated code version 1.0.0");


namespace ros2_plugin_proto {
namespace srv {

class RosRpcWrapperSyncService : public aimrt::rpc::ServiceBase {
 public:
  RosRpcWrapperSyncService();
  ~RosRpcWrapperSyncService() override = default;

  virtual aimrt::rpc::Status RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) {
    return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
};

class RosRpcWrapperAsyncService : public aimrt::rpc::ServiceBase {
 public:
  RosRpcWrapperAsyncService();
  ~RosRpcWrapperAsyncService() override = default;

  virtual void RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    callback(aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED));
  }
};

class RosRpcWrapperCoService : public aimrt::rpc::CoServiceBase {
 public:
  RosRpcWrapperCoService();
  ~RosRpcWrapperCoService() override = default;

  virtual aimrt::co::Task<aimrt::rpc::Status> RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) {
    co_return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
  }
};

bool RegisterRosRpcWrapperClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
bool RegisterRosRpcWrapperClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref);

class RosRpcWrapperSyncProxy : public aimrt::rpc::SyncProxyBase {
 public:
  explicit RosRpcWrapperSyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit RosRpcWrapperSyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~RosRpcWrapperSyncProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref, service_name);
  }

  aimrt::rpc::Status RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp);

  aimrt::rpc::Status RosRpcWrapper(
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) {
    return RosRpcWrapper(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class RosRpcWrapperAsyncProxy : public aimrt::rpc::AsyncProxyBase {
 public:
  explicit RosRpcWrapperAsyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit RosRpcWrapperAsyncProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~RosRpcWrapperAsyncProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref, service_name);
  }

  void RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback);

  void RosRpcWrapper(
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp,
      std::function<void(aimrt::rpc::Status)>&& callback) {
    RosRpcWrapper(aimrt::rpc::ContextRef(), req, rsp, std::move(callback));
  }
};

class RosRpcWrapperFutureProxy : public aimrt::rpc::FutureProxyBase {
 public:
  explicit RosRpcWrapperFutureProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit RosRpcWrapperFutureProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~RosRpcWrapperFutureProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref, service_name);
  }

  std::future<aimrt::rpc::Status> RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp);

  std::future<aimrt::rpc::Status> RosRpcWrapper(
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) {
    return RosRpcWrapper(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class RosRpcWrapperCoProxy : public aimrt::rpc::CoProxyBase {
 public:
  explicit RosRpcWrapperCoProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref);
  explicit RosRpcWrapperCoProxy(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name);
  ~RosRpcWrapperCoProxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref);
  }

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref, std::string_view service_name) {
    return RegisterRosRpcWrapperClientFunc(rpc_handle_ref, service_name);
  }

  aimrt::co::Task<aimrt::rpc::Status> RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp);

  aimrt::co::Task<aimrt::rpc::Status> RosRpcWrapper(
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) {
    return RosRpcWrapper(aimrt::rpc::ContextRef(), req, rsp);
  }
};

class RosRpcWrapperCoClient {
 public:
  void Init(const std::shared_ptr<::aimrt::context::Context> & ctx_ptr, std::string service_name = "");

 public:
  ::aimrt::context::res::Client<RosRpcWrapper_Request, RosRpcWrapper_Response> RosRpcWrapper;

 public:
  static std::vector<std::string> GetMethodNames(std::string service_name = {});

};

class RosRpcWrapperAimRTImpl;

class RosRpcWrapperCoServer : public std::enable_shared_from_this<RosRpcWrapperCoServer> {
 public:
  void Init(const std::shared_ptr<::aimrt::context::Context> & ctx_ptr, std::string service_name = "");

 public:
  ::aimrt::context::res::Server<RosRpcWrapper_Request, RosRpcWrapper_Response> RosRpcWrapper;

 public:
  static std::vector<std::string> GetMethodNames(std::string service_name = {});

 private:
  std::weak_ptr<::aimrt::context::Context> ctx_weak_ptr_;
  std::shared_ptr<RosRpcWrapperAimRTImpl> impl_;
};

class RosRpcWrapperAimRTImpl final : public RosRpcWrapperCoService {
 public:
  explicit RosRpcWrapperAimRTImpl(
      std::weak_ptr<::aimrt::context::Context> weak_ctx_ptr,
      std::shared_ptr<RosRpcWrapperCoServer> res);

  aimrt::co::Task<aimrt::rpc::Status> RosRpcWrapper(
      aimrt::rpc::ContextRef ctx_ref,
      const RosRpcWrapper_Request& req,
      RosRpcWrapper_Response& rsp) override;

 private:
  std::weak_ptr<::aimrt::context::Context> weak_ctx_ptr_;
  std::shared_ptr<RosRpcWrapperCoServer> res_;
};

}  // namespace srv
}  // namespace ros2_plugin_proto
