#!/usr/bin/env python3
"""Prepare a small TTMD6 candidate subset for the existing A3 IK probe."""

from __future__ import annotations

if __package__ in {None, ""}:
    import sys

    from pathlib import Path

    _ROOT = Path(__file__).resolve().parents[2]
    if str(_ROOT) not in sys.path:
        sys.path.insert(0, str(_ROOT))
    del _ROOT

import argparse
import json
import re
from pathlib import Path

import numpy as np


def quat_xyzw_to_matrix(quat: np.ndarray) -> np.ndarray:
    x, y, z, w = quat
    return np.asarray(
        [
            [1.0 - 2.0 * (y * y + z * z), 2.0 * (x * y - z * w), 2.0 * (x * z + y * w)],
            [2.0 * (x * y + z * w), 1.0 - 2.0 * (x * x + z * z), 2.0 * (y * z - x * w)],
            [2.0 * (x * z - y * w), 2.0 * (y * z + x * w), 1.0 - 2.0 * (x * x + y * y)],
        ],
        dtype=np.float64,
    )


def matrix_to_quat_xyzw(matrix: np.ndarray) -> np.ndarray:
    # Stable enough for the orthonormal candidate frames generated by the
    # previous stage; normalize again before returning.
    trace = float(np.trace(matrix))
    if trace > 0.0:
        s = 2.0 * np.sqrt(trace + 1.0)
        w = 0.25 * s
        x = (matrix[2, 1] - matrix[1, 2]) / s
        y = (matrix[0, 2] - matrix[2, 0]) / s
        z = (matrix[1, 0] - matrix[0, 1]) / s
    else:
        diagonal = np.diag(matrix)
        index = int(np.argmax(diagonal))
        if index == 0:
            s = 2.0 * np.sqrt(max(1.0 + matrix[0, 0] - matrix[1, 1] - matrix[2, 2], 1e-12))
            x = 0.25 * s
            y = (matrix[0, 1] + matrix[1, 0]) / s
            z = (matrix[0, 2] + matrix[2, 0]) / s
            w = (matrix[2, 1] - matrix[1, 2]) / s
        elif index == 1:
            s = 2.0 * np.sqrt(max(1.0 + matrix[1, 1] - matrix[0, 0] - matrix[2, 2], 1e-12))
            x = (matrix[0, 1] + matrix[1, 0]) / s
            y = 0.25 * s
            z = (matrix[1, 2] + matrix[2, 1]) / s
            w = (matrix[0, 2] - matrix[2, 0]) / s
        else:
            s = 2.0 * np.sqrt(max(1.0 + matrix[2, 2] - matrix[0, 0] - matrix[1, 1], 1e-12))
            x = (matrix[0, 2] + matrix[2, 0]) / s
            y = (matrix[1, 2] + matrix[2, 1]) / s
            z = 0.25 * s
            w = (matrix[1, 0] - matrix[0, 1]) / s
    quat = np.asarray([x, y, z, w], dtype=np.float64)
    return quat / max(float(np.linalg.norm(quat)), 1e-12)


def compose_quat_xyzw(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    x1, y1, z1, w1 = left
    x2, y2, z2, w2 = right
    out = np.asarray(
        [
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
            w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
        ],
        dtype=np.float64,
    )
    return out / max(float(np.linalg.norm(out)), 1e-12)


def select_records(records: list[dict], per_class: int) -> list[dict]:
    selected = []
    counts: dict[int, int] = {}
    for record in records:
        class_id = int(record["source_id"].split("_")[0].replace("class", ""))
        if counts.get(class_id, 0) >= per_class:
            continue
        selected.append(record)
        counts[class_id] = counts.get(class_id, 0) + 1
    return selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("candidate_manifest", type=Path)
    parser.add_argument("--base-config", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--records-per-class", type=int, default=1)
    parser.add_argument("--source-fps", type=float, default=120.0)
    args = parser.parse_args()

    candidate_manifest = json.loads(args.candidate_manifest.read_text(encoding="utf-8"))
    source_records = select_records(candidate_manifest["records"], args.records_per_class)
    output_root = args.output_root
    target_root = output_root / "target_npz"
    spec_root = output_root / "target_specs"
    target_root.mkdir(parents=True, exist_ok=True)
    spec_root.mkdir(parents=True, exist_ok=True)

    base_text = args.base_config.read_text(encoding="utf-8")
    base_match = re.search(r"(?m)^\s*position_m:\s*\[([^\]]+)\]", base_text)
    quat_match = re.search(r"(?m)^\s*quat_xyzw:\s*\[([^\]]+)\]", base_text)
    if not base_match or not quat_match:
        raise ValueError("base config must contain robot_base position_m and quat_xyzw")
    base_pos = np.asarray([float(x.strip()) for x in base_match.group(1).split(",")], dtype=np.float64)
    base_quat = np.asarray([float(x.strip()) for x in quat_match.group(1).split(",")], dtype=np.float64)
    base_rot = quat_xyzw_to_matrix(base_quat)

    samples = []
    for source_record in source_records:
        for variant in source_record["variants"]:
            variant_path = Path(variant["path"])
            data = np.load(variant_path)
            pos_b = data["racket_target_pos_b"]
            vel_b = data["racket_target_vel_b"]
            normal_b = data["racket_target_normal_b"]
            tangent_b = data["racket_target_tangent_b"]
            up_b = np.cross(tangent_b, normal_b)
            up_b /= np.maximum(np.linalg.norm(up_b, axis=1, keepdims=True), 1e-12)
            quat_b = np.asarray(
                [matrix_to_quat_xyzw(np.stack([tangent_b[i], normal_b[i], up_b[i]], axis=1)) for i in range(len(pos_b))]
            )
            pos_w = base_pos[None, :] + np.einsum("ij,tj->ti", base_rot, pos_b)
            vel_w = np.einsum("ij,tj->ti", base_rot, vel_b)
            quat_w = np.asarray([compose_quat_xyzw(base_quat, quat_b[i]) for i in range(len(pos_b))])
            candidate_frame = int(data["candidate_frame_only"])
            episode_id = variant["variant_id"]
            target_npz = target_root / f"{episode_id}.npz"
            target_spec = spec_root / f"{episode_id}.json"
            np.savez_compressed(
                target_npz,
                racket_pos=pos_w,
                racket_vel=vel_w,
                racket_quat=quat_w,
                racket_pos_base=pos_b,
                racket_vel_base=vel_b,
                racket_normal_base=normal_b,
                racket_tangent_base=tangent_b,
                racket_normal_w=np.einsum("ij,tj->ti", base_rot, normal_b),
                racket_tangent_w=np.einsum("ij,tj->ti", base_rot, tangent_b),
                hit_index=np.asarray(candidate_frame, dtype=np.int64),
                source_fps=np.asarray(float(args.source_fps), dtype=np.float64),
                hit_index_status=np.asarray("candidate_only"),
            )
            target_spec.write_text(
                json.dumps(
                    {
                        "episode_id": episode_id,
                        "source_id": source_record["source_id"],
                        "target_npz": str(target_npz),
                        "coordinate_status": "hypothesis_only",
                        "hit_index_status": "candidate_only",
                        "orientation_status": "constructed_heuristic",
                        "training_eligible": False,
                    },
                    ensure_ascii=True,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            samples.append(
                {
                    "episode_id": episode_id,
                    "source_id": source_record["source_id"],
                    "target_npz": str(target_npz),
                    "target_spec_json": str(target_spec),
                    "candidate_hit_index": candidate_frame,
                    "candidate_hit_index_status": "candidate_only",
                    "orientation_status": "constructed_heuristic",
                    "coordinate_status": "hypothesis_only",
                    "training_eligible": False,
                }
            )

    manifest_path = output_root / "retarget_target_manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "dataset": "TTMD6",
                "stage": "a3_ik_probe_targets_v0",
                "source_candidate_manifest": str(args.candidate_manifest),
                "base_config": str(args.base_config),
                "base_pose_source": "existing_A3_fixed_base_config",
                "coordinate_status": "hypothesis_only",
                "hit_index_status": "candidate_only",
                "training_eligible": False,
                "samples": samples,
            },
            ensure_ascii=True,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"prepared {len(samples)} A3 IK probe targets from {len(source_records)} source clips")
    print(manifest_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
