set(_AMENT_PACKAGE_NAME "mujoco_sim_msgs")
set(mujoco_sim_msgs_VERSION "0.1.0")
set(mujoco_sim_msgs_MAINTAINER "agibotdev <agibotdev@agibot.com>")
set(mujoco_sim_msgs_BUILD_DEPENDS "geometry_msgs" "sensor_msgs" "std_msgs")
set(mujoco_sim_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(mujoco_sim_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "sensor_msgs" "std_msgs")
set(mujoco_sim_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(mujoco_sim_msgs_EXEC_DEPENDS "rosidl_default_runtime" "geometry_msgs" "sensor_msgs" "std_msgs")
set(mujoco_sim_msgs_TEST_DEPENDS )
set(mujoco_sim_msgs_GROUP_DEPENDS )
set(mujoco_sim_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(mujoco_sim_msgs_DEPRECATED "")
set(mujoco_sim_msgs_EXPORT_TAGS)
list(APPEND mujoco_sim_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
