// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_manipulator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_time_5fmanipulator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_time_5fmanipulator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_time_5fmanipulator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_time_5fmanipulator_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_time_5fmanipulator_2eproto;
namespace aimrt {
namespace protocols {
namespace time_manipulator_plugin {
class CommonRsp;
struct CommonRspDefaultTypeInternal;
extern CommonRspDefaultTypeInternal _CommonRsp_default_instance_;
class GetTimeRatioReq;
struct GetTimeRatioReqDefaultTypeInternal;
extern GetTimeRatioReqDefaultTypeInternal _GetTimeRatioReq_default_instance_;
class PauseReq;
struct PauseReqDefaultTypeInternal;
extern PauseReqDefaultTypeInternal _PauseReq_default_instance_;
class SetTimeRatioReq;
struct SetTimeRatioReqDefaultTypeInternal;
extern SetTimeRatioReqDefaultTypeInternal _SetTimeRatioReq_default_instance_;
}  // namespace time_manipulator_plugin
}  // namespace protocols
}  // namespace aimrt
PROTOBUF_NAMESPACE_OPEN
template<> ::aimrt::protocols::time_manipulator_plugin::CommonRsp* Arena::CreateMaybeMessage<::aimrt::protocols::time_manipulator_plugin::CommonRsp>(Arena*);
template<> ::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq* Arena::CreateMaybeMessage<::aimrt::protocols::time_manipulator_plugin::GetTimeRatioReq>(Arena*);
template<> ::aimrt::protocols::time_manipulator_plugin::PauseReq* Arena::CreateMaybeMessage<::aimrt::protocols::time_manipulator_plugin::PauseReq>(Arena*);
template<> ::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq* Arena::CreateMaybeMessage<::aimrt::protocols::time_manipulator_plugin::SetTimeRatioReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aimrt {
namespace protocols {
namespace time_manipulator_plugin {

// ===================================================================

class CommonRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.time_manipulator_plugin.CommonRsp) */ {
 public:
  inline CommonRsp() : CommonRsp(nullptr) {}
  ~CommonRsp() override;
  explicit PROTOBUF_CONSTEXPR CommonRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CommonRsp(const CommonRsp& from);
  CommonRsp(CommonRsp&& from) noexcept
    : CommonRsp() {
    *this = ::std::move(from);
  }

  inline CommonRsp& operator=(const CommonRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommonRsp& operator=(CommonRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CommonRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const CommonRsp* internal_default_instance() {
    return reinterpret_cast<const CommonRsp*>(
               &_CommonRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CommonRsp& a, CommonRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(CommonRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommonRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CommonRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CommonRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CommonRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CommonRsp& from) {
    CommonRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommonRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.time_manipulator_plugin.CommonRsp";
  }
  protected:
  explicit CommonRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 3,
    kTimeRatioFieldNumber = 1,
    kCodeFieldNumber = 2,
  };
  // string msg = 3;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // double time_ratio = 1;
  void clear_time_ratio();
  double time_ratio() const;
  void set_time_ratio(double value);
  private:
  double _internal_time_ratio() const;
  void _internal_set_time_ratio(double value);
  public:

  // uint32 code = 2;
  void clear_code();
  uint32_t code() const;
  void set_code(uint32_t value);
  private:
  uint32_t _internal_code() const;
  void _internal_set_code(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.time_manipulator_plugin.CommonRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    double time_ratio_;
    uint32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_time_5fmanipulator_2eproto;
};
// -------------------------------------------------------------------

class SetTimeRatioReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq) */ {
 public:
  inline SetTimeRatioReq() : SetTimeRatioReq(nullptr) {}
  ~SetTimeRatioReq() override;
  explicit PROTOBUF_CONSTEXPR SetTimeRatioReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetTimeRatioReq(const SetTimeRatioReq& from);
  SetTimeRatioReq(SetTimeRatioReq&& from) noexcept
    : SetTimeRatioReq() {
    *this = ::std::move(from);
  }

  inline SetTimeRatioReq& operator=(const SetTimeRatioReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetTimeRatioReq& operator=(SetTimeRatioReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetTimeRatioReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetTimeRatioReq* internal_default_instance() {
    return reinterpret_cast<const SetTimeRatioReq*>(
               &_SetTimeRatioReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SetTimeRatioReq& a, SetTimeRatioReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SetTimeRatioReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetTimeRatioReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetTimeRatioReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetTimeRatioReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetTimeRatioReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetTimeRatioReq& from) {
    SetTimeRatioReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetTimeRatioReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq";
  }
  protected:
  explicit SetTimeRatioReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExecutorNameFieldNumber = 1,
    kTimeRatioFieldNumber = 2,
  };
  // string executor_name = 1;
  void clear_executor_name();
  const std::string& executor_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_executor_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_executor_name();
  PROTOBUF_NODISCARD std::string* release_executor_name();
  void set_allocated_executor_name(std::string* executor_name);
  private:
  const std::string& _internal_executor_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_executor_name(const std::string& value);
  std::string* _internal_mutable_executor_name();
  public:

  // double time_ratio = 2;
  void clear_time_ratio();
  double time_ratio() const;
  void set_time_ratio(double value);
  private:
  double _internal_time_ratio() const;
  void _internal_set_time_ratio(double value);
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr executor_name_;
    double time_ratio_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_time_5fmanipulator_2eproto;
};
// -------------------------------------------------------------------

class PauseReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.time_manipulator_plugin.PauseReq) */ {
 public:
  inline PauseReq() : PauseReq(nullptr) {}
  ~PauseReq() override;
  explicit PROTOBUF_CONSTEXPR PauseReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PauseReq(const PauseReq& from);
  PauseReq(PauseReq&& from) noexcept
    : PauseReq() {
    *this = ::std::move(from);
  }

  inline PauseReq& operator=(const PauseReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PauseReq& operator=(PauseReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PauseReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PauseReq* internal_default_instance() {
    return reinterpret_cast<const PauseReq*>(
               &_PauseReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PauseReq& a, PauseReq& b) {
    a.Swap(&b);
  }
  inline void Swap(PauseReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PauseReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PauseReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PauseReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PauseReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PauseReq& from) {
    PauseReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PauseReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.time_manipulator_plugin.PauseReq";
  }
  protected:
  explicit PauseReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExecutorNameFieldNumber = 1,
  };
  // string executor_name = 1;
  void clear_executor_name();
  const std::string& executor_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_executor_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_executor_name();
  PROTOBUF_NODISCARD std::string* release_executor_name();
  void set_allocated_executor_name(std::string* executor_name);
  private:
  const std::string& _internal_executor_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_executor_name(const std::string& value);
  std::string* _internal_mutable_executor_name();
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.time_manipulator_plugin.PauseReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr executor_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_time_5fmanipulator_2eproto;
};
// -------------------------------------------------------------------

class GetTimeRatioReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq) */ {
 public:
  inline GetTimeRatioReq() : GetTimeRatioReq(nullptr) {}
  ~GetTimeRatioReq() override;
  explicit PROTOBUF_CONSTEXPR GetTimeRatioReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetTimeRatioReq(const GetTimeRatioReq& from);
  GetTimeRatioReq(GetTimeRatioReq&& from) noexcept
    : GetTimeRatioReq() {
    *this = ::std::move(from);
  }

  inline GetTimeRatioReq& operator=(const GetTimeRatioReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTimeRatioReq& operator=(GetTimeRatioReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetTimeRatioReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetTimeRatioReq* internal_default_instance() {
    return reinterpret_cast<const GetTimeRatioReq*>(
               &_GetTimeRatioReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetTimeRatioReq& a, GetTimeRatioReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GetTimeRatioReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTimeRatioReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetTimeRatioReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetTimeRatioReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetTimeRatioReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetTimeRatioReq& from) {
    GetTimeRatioReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetTimeRatioReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq";
  }
  protected:
  explicit GetTimeRatioReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExecutorNameFieldNumber = 1,
  };
  // string executor_name = 1;
  void clear_executor_name();
  const std::string& executor_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_executor_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_executor_name();
  PROTOBUF_NODISCARD std::string* release_executor_name();
  void set_allocated_executor_name(std::string* executor_name);
  private:
  const std::string& _internal_executor_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_executor_name(const std::string& value);
  std::string* _internal_mutable_executor_name();
  public:

  // @@protoc_insertion_point(class_scope:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr executor_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_time_5fmanipulator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CommonRsp

// double time_ratio = 1;
inline void CommonRsp::clear_time_ratio() {
  _impl_.time_ratio_ = 0;
}
inline double CommonRsp::_internal_time_ratio() const {
  return _impl_.time_ratio_;
}
inline double CommonRsp::time_ratio() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.CommonRsp.time_ratio)
  return _internal_time_ratio();
}
inline void CommonRsp::_internal_set_time_ratio(double value) {
  
  _impl_.time_ratio_ = value;
}
inline void CommonRsp::set_time_ratio(double value) {
  _internal_set_time_ratio(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.CommonRsp.time_ratio)
}

// uint32 code = 2;
inline void CommonRsp::clear_code() {
  _impl_.code_ = 0u;
}
inline uint32_t CommonRsp::_internal_code() const {
  return _impl_.code_;
}
inline uint32_t CommonRsp::code() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.CommonRsp.code)
  return _internal_code();
}
inline void CommonRsp::_internal_set_code(uint32_t value) {
  
  _impl_.code_ = value;
}
inline void CommonRsp::set_code(uint32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.CommonRsp.code)
}

// string msg = 3;
inline void CommonRsp::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& CommonRsp::msg() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.CommonRsp.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CommonRsp::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.CommonRsp.msg)
}
inline std::string* CommonRsp::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.time_manipulator_plugin.CommonRsp.msg)
  return _s;
}
inline const std::string& CommonRsp::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void CommonRsp::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* CommonRsp::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* CommonRsp::release_msg() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.time_manipulator_plugin.CommonRsp.msg)
  return _impl_.msg_.Release();
}
inline void CommonRsp::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.time_manipulator_plugin.CommonRsp.msg)
}

// -------------------------------------------------------------------

// SetTimeRatioReq

// string executor_name = 1;
inline void SetTimeRatioReq::clear_executor_name() {
  _impl_.executor_name_.ClearToEmpty();
}
inline const std::string& SetTimeRatioReq::executor_name() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.executor_name)
  return _internal_executor_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SetTimeRatioReq::set_executor_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.executor_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.executor_name)
}
inline std::string* SetTimeRatioReq::mutable_executor_name() {
  std::string* _s = _internal_mutable_executor_name();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.executor_name)
  return _s;
}
inline const std::string& SetTimeRatioReq::_internal_executor_name() const {
  return _impl_.executor_name_.Get();
}
inline void SetTimeRatioReq::_internal_set_executor_name(const std::string& value) {
  
  _impl_.executor_name_.Set(value, GetArenaForAllocation());
}
inline std::string* SetTimeRatioReq::_internal_mutable_executor_name() {
  
  return _impl_.executor_name_.Mutable(GetArenaForAllocation());
}
inline std::string* SetTimeRatioReq::release_executor_name() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.executor_name)
  return _impl_.executor_name_.Release();
}
inline void SetTimeRatioReq::set_allocated_executor_name(std::string* executor_name) {
  if (executor_name != nullptr) {
    
  } else {
    
  }
  _impl_.executor_name_.SetAllocated(executor_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.executor_name_.IsDefault()) {
    _impl_.executor_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.executor_name)
}

// double time_ratio = 2;
inline void SetTimeRatioReq::clear_time_ratio() {
  _impl_.time_ratio_ = 0;
}
inline double SetTimeRatioReq::_internal_time_ratio() const {
  return _impl_.time_ratio_;
}
inline double SetTimeRatioReq::time_ratio() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.time_ratio)
  return _internal_time_ratio();
}
inline void SetTimeRatioReq::_internal_set_time_ratio(double value) {
  
  _impl_.time_ratio_ = value;
}
inline void SetTimeRatioReq::set_time_ratio(double value) {
  _internal_set_time_ratio(value);
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.SetTimeRatioReq.time_ratio)
}

// -------------------------------------------------------------------

// PauseReq

// string executor_name = 1;
inline void PauseReq::clear_executor_name() {
  _impl_.executor_name_.ClearToEmpty();
}
inline const std::string& PauseReq::executor_name() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.PauseReq.executor_name)
  return _internal_executor_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PauseReq::set_executor_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.executor_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.PauseReq.executor_name)
}
inline std::string* PauseReq::mutable_executor_name() {
  std::string* _s = _internal_mutable_executor_name();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.time_manipulator_plugin.PauseReq.executor_name)
  return _s;
}
inline const std::string& PauseReq::_internal_executor_name() const {
  return _impl_.executor_name_.Get();
}
inline void PauseReq::_internal_set_executor_name(const std::string& value) {
  
  _impl_.executor_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PauseReq::_internal_mutable_executor_name() {
  
  return _impl_.executor_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PauseReq::release_executor_name() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.time_manipulator_plugin.PauseReq.executor_name)
  return _impl_.executor_name_.Release();
}
inline void PauseReq::set_allocated_executor_name(std::string* executor_name) {
  if (executor_name != nullptr) {
    
  } else {
    
  }
  _impl_.executor_name_.SetAllocated(executor_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.executor_name_.IsDefault()) {
    _impl_.executor_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.time_manipulator_plugin.PauseReq.executor_name)
}

// -------------------------------------------------------------------

// GetTimeRatioReq

// string executor_name = 1;
inline void GetTimeRatioReq::clear_executor_name() {
  _impl_.executor_name_.ClearToEmpty();
}
inline const std::string& GetTimeRatioReq::executor_name() const {
  // @@protoc_insertion_point(field_get:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq.executor_name)
  return _internal_executor_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetTimeRatioReq::set_executor_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.executor_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq.executor_name)
}
inline std::string* GetTimeRatioReq::mutable_executor_name() {
  std::string* _s = _internal_mutable_executor_name();
  // @@protoc_insertion_point(field_mutable:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq.executor_name)
  return _s;
}
inline const std::string& GetTimeRatioReq::_internal_executor_name() const {
  return _impl_.executor_name_.Get();
}
inline void GetTimeRatioReq::_internal_set_executor_name(const std::string& value) {
  
  _impl_.executor_name_.Set(value, GetArenaForAllocation());
}
inline std::string* GetTimeRatioReq::_internal_mutable_executor_name() {
  
  return _impl_.executor_name_.Mutable(GetArenaForAllocation());
}
inline std::string* GetTimeRatioReq::release_executor_name() {
  // @@protoc_insertion_point(field_release:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq.executor_name)
  return _impl_.executor_name_.Release();
}
inline void GetTimeRatioReq::set_allocated_executor_name(std::string* executor_name) {
  if (executor_name != nullptr) {
    
  } else {
    
  }
  _impl_.executor_name_.SetAllocated(executor_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.executor_name_.IsDefault()) {
    _impl_.executor_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aimrt.protocols.time_manipulator_plugin.GetTimeRatioReq.executor_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace time_manipulator_plugin
}  // namespace protocols
}  // namespace aimrt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_time_5fmanipulator_2eproto
