"""Strike-spec inverse planner tests (ball_contact + strike_spec_planner).

Covers: contact-port equivalence against the training-side torch
virtual_ball.predict_paddle_contact (5 hand-fed cases, expected outputs
generated by an INDEPENDENT scalar-math port of the same equations),
round-trip inversion, the report's tilt-sensitivity anchor, and graceful
None returns for unreachable targets / blown speed budgets.
"""

import numpy as np

from hope_planner.ball_contact import orient_normal, predict_paddle_contact
from hope_planner.ball_trajectory_predictor import BallTrajectoryPredictor
from hope_planner.constants import BallPhysics, PlannerConfig, TableParams
from hope_planner.strike_spec_planner import StrikeSpecPlanner

PHYS = BallPhysics()
CFG = PlannerConfig()
TAB = TableParams()


# --------------------------------------------------------------------- #
# (d) contact port equivalence vs the torch virtual_ball semantics
# --------------------------------------------------------------------- #
# Expected outputs come from a second, INDEPENDENT scalar-math port of
# hope_training/.../mdp/virtual_ball.predict_paddle_contact written directly
# from the torch source (explicit component cross/dot, math.exp/hypot — no
# shared code with hope_planner.ball_contact), evaluated at the venue params
# mirrored in constants.py: R=0.02, c=2/3, a_t=0.52, b_t=0.0, mu=0.5,
# e = 0.759*exp(-0.0441*|u_n|) clamped [0.05, 0.95].
#
# Each case: (v_minus, v_r, n, omega_minus) -> (v_plus, omega_plus).
_CONTACT_CASES = [
    # 1. head-on, no spin, static-face frame: hand-checkable —
    #    u_n = -5, e = 0.759*exp(-0.2205) = 0.608807, v+x = -4 + (1+e)*5.
    (
        [-4.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0],
        [4.04403642879, 0.0, 0.0],
        [0.0, 0.0, 0.0],
    ),
    # 2. oblique face + moving racket, no spin (e=0.599871, s=raw=0.372971).
    (
        [-4.0, 0.5, -1.0], [1.2, 0.0, 0.3], [1.0, 0.0, 0.15], [0.0, 0.0, 0.0],
        [4.401705349006, 0.240000000362, 0.530655801974],
        [-2.892638825246, 20.055629188374, 19.284258834975],
    ),
    # 3. topspin ball on a tilted face (spin feeds u through omega x r).
    (
        [-3.5, 0.0, -1.5], [0.8, 0.0, 0.5], [0.9, 0.1, 0.2], [0.0, -60.0, 10.0],
        [3.50353063379, 0.646855980446, 1.237437862686],
        [-11.676072567609, 25.968703777516, 19.557974665484],
    ),
    # 4. grazing hit: friction-cone cap BINDS (raw=3.12 > cap=0.863128).
    (
        [-1.0, 6.0, 0.0], [0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0],
        [0.726255421415, 5.136872288717, 0.0],
        [0.0, 0.0, 64.7345782815],
    ),
    # 5. same as case 2 but the normal handed in FLIPPED — orient_normal
    #    must recover the identical outcome.
    (
        [-4.0, 0.5, -1.0], [1.2, 0.0, 0.3], [-1.0, 0.0, -0.15], [0.0, 0.0, 0.0],
        [4.401705349006, 0.240000000362, 0.530655801974],
        [-2.892638825246, 20.055629188374, 19.284258834975],
    ),
]


def test_contact_port_matches_torch_reference_cases():
    for i, (vm, vr, n, w, v_exp, w_exp) in enumerate(_CONTACT_CASES, start=1):
        v_plus, w_plus = predict_paddle_contact(
            np.array(vm), np.array(vr), np.array(n), np.array(w), PHYS, CFG
        )
        assert np.allclose(v_plus, v_exp, atol=1e-9), f"case {i} v_plus"
        assert np.allclose(w_plus, w_exp, atol=1e-9), f"case {i} omega_plus"


def test_orient_normal_flips_receding_normal():
    v_minus = np.array([-4.0, 0.0, 0.0])
    v_r = np.zeros(3)
    # (v_minus - v_r) . (-x) > 0 -> flipped to +x (toward the incoming ball).
    n = orient_normal(np.array([-2.0, 0.0, 0.0]), v_minus, v_r)
    assert np.allclose(n, [1.0, 0.0, 0.0], atol=1e-8)
    # Already approaching -> kept (and normalized).
    n = orient_normal(np.array([3.0, 0.0, 0.0]), v_minus, v_r)
    assert np.allclose(n, [1.0, 0.0, 0.0], atol=1e-8)


def test_contact_grazing_cap_conserves_normal_law():
    """When the cap binds, the normal channel must still follow e(u_n)."""
    v_plus, _ = predict_paddle_contact(
        np.array([-1.0, 6.0, 0.0]), np.zeros(3), np.array([1.0, 0.0, 0.0]),
        np.zeros(3), PHYS, CFG,
    )
    e = np.clip(CFG.e_exp_g1 * np.exp(CFG.e_exp_g2 * 1.0), 0.05, 0.95)
    assert np.isclose(v_plus[0], -1.0 + (1.0 + e) * 1.0, atol=1e-12)


# --------------------------------------------------------------------- #
# (a) round-trip: forward-sim a known spec, invert its landing
# --------------------------------------------------------------------- #


def _forward_landing(p_strike, v_ball, w_ball, n, v_r):
    """Contact + flight with the same shared physics the planner uses."""
    pred = BallTrajectoryPredictor(PHYS, CFG, TAB)
    v_plus, w_plus = predict_paddle_contact(v_ball, v_r, n, w_ball, PHYS, CFG)
    return pred.integrate_to_table_plane(p_strike, v_plus, w_plus)


def test_round_trip_recovers_landing_within_2cm():
    p_strike = np.array([0.0, -0.7625, 0.3])
    v_ball = np.array([-4.0, 0.3, -0.8])
    w_ball = np.array([0.0, -30.0, 0.0])

    # Known spec: opened face, forward drive + face-up tangential component.
    n = np.array([0.92, -0.06, 0.39])
    n = n / np.linalg.norm(n)
    b1 = np.cross([0.0, 0.0, 1.0], n)
    b1 = b1 / np.linalg.norm(b1)
    b2 = np.cross(n, b1)
    v_r = 1.8 * n + 0.5 * b2

    landing = _forward_landing(p_strike, v_ball, w_ball, n, v_r)
    assert landing is not None
    target_xy, _ = landing
    # Sanity: the generated shot lands on the opponent half.
    assert TAB.net_x < target_xy[0] < TAB.length

    planner = StrikeSpecPlanner(physics=PHYS, config=CFG, table=TAB)
    spec = planner.solve(p_strike, v_ball, w_ball, target_xy, racket_speed_budget=10.0)
    assert spec is not None
    assert np.linalg.norm(spec.landing_xy - target_xy) < 0.02
    assert spec.residual_m < planner.TOL_M
    assert np.linalg.norm(spec.v_r) <= 10.0

    # The spec must be self-consistent: replaying its OWN control variables
    # (n, v_r) through the shared forward model reproduces its landing.
    replay = _forward_landing(p_strike, v_ball, w_ball, spec.n, spec.v_r)
    assert replay is not None
    assert np.linalg.norm(replay[0] - spec.landing_xy) < 1e-9

    # Decomposition consistency: v_r == v_n * n + v_t in the face basis.
    b1s, b2s = spec.face_basis
    v_rebuilt = spec.v_n_signed * spec.n + spec.v_t_vec[0] * b1s + spec.v_t_vec[1] * b2s
    assert np.allclose(v_rebuilt, spec.v_r, atol=1e-9)


# --------------------------------------------------------------------- #
# (b) sensitivity anchor: report's +-5 deg -> +-0.3 m (~0.06 m/deg)
# --------------------------------------------------------------------- #


def test_tilt_sensitivity_anchor_at_typical_venue_return():
    """A typical flat venue return (u_n ~ 5 m/s) must show a landing tilt
    sensitivity on the order of 0.05-0.08 m/deg (fit-report anchor: +-5 deg
    face error -> +-0.3 m landing). Order-of-magnitude assert only — the
    exact slope depends on loft (near the range-optimal launch angle the
    PITCH slope legitimately shrinks toward zero, which is why the max of
    the two tilt channels is anchored, not each one)."""
    cfg = PlannerConfig(delta_t_flight=0.45)  # flat-return seed
    planner = StrikeSpecPlanner(physics=PHYS, config=cfg, table=TAB)
    p_strike = np.array([0.0, -0.7625, 0.25])
    v_ball = np.array([-3.5, 0.2, -0.6])

    spec = planner.solve(
        p_strike, v_ball, None, np.array([2.2, -0.6]), racket_speed_budget=12.0
    )
    assert spec is not None

    u_n = abs(np.dot(v_ball - spec.v_r, spec.n))
    assert 4.0 < u_n < 6.5  # the anchor regime the report quotes

    d_pitch = float(np.linalg.norm(spec.d_landing_d_pitch))
    d_yaw = float(np.linalg.norm(spec.d_landing_d_yaw))
    # Order of magnitude around 0.05-0.08 m/deg: same decade, not exact.
    assert 0.01 < max(d_pitch, d_yaw) < 0.3
    assert 0.01 < d_yaw < 0.3

    # Velocity-channel budget must be finite and sane: ~0.1-2 m per m/s.
    d_v_n = float(np.linalg.norm(spec.d_landing_d_v_n))
    d_v_t = float(np.linalg.norm(spec.d_landing_d_v_t))
    assert 0.05 < d_v_n < 3.0
    assert 0.01 < d_v_t < 3.0


# --------------------------------------------------------------------- #
# (c) graceful None: unreachable target / speed budget exceeded
# --------------------------------------------------------------------- #


def test_unreachable_target_returns_none():
    planner = StrikeSpecPlanner(physics=PHYS, config=CFG, table=TAB)
    p_strike = np.array([0.0, -0.7625, 0.3])
    v_ball = np.array([-4.0, 0.3, -0.8])
    # 8 m downrange is far beyond any budget-6 racket motion at this height.
    spec = planner.solve(
        p_strike, v_ball, None, np.array([8.0, -0.7625]), racket_speed_budget=6.0
    )
    assert spec is None


def test_speed_budget_exceeded_returns_none():
    planner = StrikeSpecPlanner(physics=PHYS, config=CFG, table=TAB)
    p_strike = np.array([0.0, -0.7625, 0.3])
    v_ball = np.array([-4.0, 0.3, -0.8])
    # A perfectly reachable target, but the budget cannot cover the ~1.2 m/s
    # racket speed the return needs -> graceful None, not a violating spec.
    spec = planner.solve(
        p_strike, v_ball, None, np.array([2.055, -0.7625]), racket_speed_budget=0.3
    )
    assert spec is None


# --------------------------------------------------------------------- #
# shared-integrator sanity
# --------------------------------------------------------------------- #


def test_integrate_to_table_plane_matches_drag_free_ballistics():
    """With k = k_m = 0 the landing must match closed-form projectile motion
    (Euler @ 1 kHz + crossing interpolation -> sub-mm agreement)."""
    phys = BallPhysics(k=0.0)
    cfg = PlannerConfig(k_m=0.0)
    pred = BallTrajectoryPredictor(phys, cfg, TAB)
    p0 = np.array([0.0, -0.7625, 0.5])
    v0 = np.array([3.0, 0.5, 1.0])
    out = pred.integrate_to_table_plane(p0, v0)
    assert out is not None
    xy, t_land = out
    # z(t) = 0.5 + v_z t - g/2 t^2 = 0
    g = 9.81
    t_exp = (v0[2] + np.sqrt(v0[2] ** 2 + 2.0 * g * p0[2])) / g
    assert abs(t_land - t_exp) < 2e-3
    assert np.allclose(xy, p0[:2] + v0[:2] * t_exp, atol=5e-3)


def test_integrate_to_table_plane_none_when_never_crossing():
    pred = BallTrajectoryPredictor(PHYS, CFG, TAB)
    # Launched from below the plane going down: never crosses z=0 from above.
    out = pred.integrate_to_table_plane(
        np.array([0.0, 0.0, -0.1]), np.array([1.0, 0.0, -1.0])
    )
    assert out is None


# --- spin-return physics anchors (franco 2026-07-04: 拍面角度是为了接旋球的) ------------------- #
def test_flat_face_flies_on_topspin():
    """A flat-face return of a 15 rev/s topspin ball kicks UP ~10 deg vs the no-spin return —
    the reason face angle exists. Anchors the omega x r coupling in the contact model."""
    import numpy as np

    from hope_planner.ball_contact import predict_paddle_contact
    from hope_planner.constants import BallPhysics, PlannerConfig

    phy, cfg = BallPhysics(), PlannerConfig()
    v_in = np.array([-5.0, 0.0, -0.5])
    v_r = np.array([1.5, 0.0, 0.2])
    n = np.array([1.0, 0.0, 0.0])
    v_flat, _ = predict_paddle_contact(v_in, v_r, n, np.zeros(3), phy, cfg)
    v_top, _ = predict_paddle_contact(v_in, v_r, n, np.array([0.0, -94.2, 0.0]), phy, cfg)
    ang_flat = np.degrees(np.arctan2(v_flat[2], np.hypot(v_flat[0], v_flat[1])))
    ang_top = np.degrees(np.arctan2(v_top[2], np.hypot(v_top[0], v_top[1])))
    assert ang_top - ang_flat > 8.0  # measured 10.7 deg at venue params
    # sidespin analogue: ~1 m/s lateral kick
    v_side, _ = predict_paddle_contact(v_in, v_r, n, np.array([0.0, 0.0, 94.2]), phy, cfg)
    assert abs(v_side[1]) > 0.7


def test_spin_ignorant_solution_misses():
    """Solve the strike spec ASSUMING no spin, then apply it to the real 15 rev/s topspin ball:
    the landing must miss by a large margin (this is why the planner needs a spin input), while
    the spin-aware solution lands on target."""
    import numpy as np

    from hope_planner.ball_contact import predict_paddle_contact
    from hope_planner.constants import BallPhysics, PlannerConfig
    from hope_planner.ball_trajectory_predictor import BallTrajectoryPredictor
    from hope_planner.constants import TableParams
    from hope_planner.strike_spec_planner import StrikeSpecPlanner

    phy, cfg, tab = BallPhysics(), PlannerConfig(), TableParams()
    planner = StrikeSpecPlanner(phy, cfg, tab)
    pred = BallTrajectoryPredictor(phy, cfg, tab)
    ball_p = np.array([0.3, -0.4, 1.0])
    ball_v = np.array([-5.0, 0.3, -0.6])
    w_top = np.array([0.0, -94.2, 0.0])
    target = np.array([2.2, -0.3])

    spec_blind = planner.solve(ball_p, ball_v, np.zeros(3), target, racket_speed_budget=10.0)
    spec_aware = planner.solve(ball_p, ball_v, w_top, target, racket_speed_budget=10.0)
    assert spec_blind is not None and spec_aware is not None
    # replay the blind spec against the REAL spinny ball
    v_plus, w_plus = predict_paddle_contact(ball_v, spec_blind.v_r, spec_blind.n, w_top, phy, cfg)
    land_blind = pred.integrate_to_table_plane(ball_p, v_plus, w_plus)
    assert land_blind is not None
    miss_blind = np.linalg.norm(np.asarray(land_blind[0][:2]) - target)
    resid_aware = np.linalg.norm(np.asarray(spec_aware.landing_xy) - target)
    # Measured at venue params: blind miss 45 mm vs aware residual 2.4 mm. NOTE the model
    # PREDICTS partial cancellation for topspin (contact kick lifts ~ a_t*R*omega, flight Magnus
    # drops ~ k_m*omega*v — both linear in omega), so the blind miss is centimeters, not the
    # folk-expected half meter. This is a falsifiable prediction: if real robot blocks fly LONG
    # on topspin, the fitted tangential transfer (a_t=0.52, form error 0.377 m/s) underestimates
    # the kick — capture that on the robot-swing calibration day.
    assert resid_aware < 0.01
    assert miss_blind > 5 * resid_aware
    assert miss_blind > 0.03
